In [1]:
import pandas as pd
import time as tm
import socket as sc

In [2]:
df = pd.read_csv('urls.csv')

In [3]:
df

                  URLS
0           google.com
1          youtube.com
2         facebook.com
3            baidu.com
4            yahoo.com
..                 ...
995        dream.co.id
996  cocolog-nifty.com
997             ptt.cc
998         legacy.com
999          mynet.com

[1000 rows x 1 columns]

In [90]:
from bs4 import BeautifulSoup

In [4]:
web=df['URLS'].tolist()
web

[' google.com',
 'youtube.com',
 'facebook.com',
 'baidu.com',
 'yahoo.com',
 'amazon.com',
 'wikipedia.org',
 'google.co.in',
 'twitter.com',
 'qq.com',
 'live.com',
 'taobao.com',
 'bing.com',
 'google.co.jp',
 'msn.com',
 'yahoo.co.jp',
 'linkedin.com',
 'sina.com.cn',
 'instagram.com',
 'weibo.com',
 'vk.com',
 'yandex.ru',
 'google.de',
 'google.ru',
 'hao123.com',
 'ebay.com',
 'reddit.com',
 'google.co.uk',
 'google.com.br',
 'mail.ru',
 't.co',
 'pinterest.com',
 'amazon.co.jp',
 'google.fr',
 'netflix.com',
 'gmw.cn',
 'tmall.com',
 '360.cn',
 'google.it',
 'microsoft.com',
 'onclickads.net',
 'google.es',
 'paypal.com',
 'sohu.com',
 'wordpress.com',
 'tumblr.com',
 'blogspot.com',
 'imgur.com',
 'xvideos.com',
 'google.com.mx',
 'naver.com',
 'stackoverflow.com',
 'apple.com',
 'chinadaily.com.cn',
 'fc2.com',
 'aliexpress.com',
 'imdb.com',
 'google.ca',
 'google.co.kr',
 'github.com',
 'ok.ru',
 'pornhub.com',
 'google.com.hk',
 'whatsapp.com',
 'diply.com',
 'jd.com',
 'amazon.de',
 'google.com.tr',
 'rakuten.co.jp',
 'craigslist.org',
 'office.com',
 'google.co.id',
 'kat.cr',
 'amazon.in',
 'tianya.cn',
 'blogger.com',
 'google.pl',
 'nicovideo.jp',
 'alibaba.com',
 'soso.com',
 'pixnet.net',
 'google.com.au',
 'go.com',
 'amazon.co.uk',
 'xhamster.com',
 'dropbox.com',
 'google.com.tw',
 'outbrain.com',
 'xinhuanet.com',
 'cntv.cn',
 'googleusercontent.com',
 'cnn.com',
 'ask.com',
 'coccoc.com',
 'booking.com',
 'bbc.co.uk',
 'popads.net',
 'youth.cn',
 'twitch.tv',
 'wikia.com',
 'microsoftonline.com',
 'quora.com',
 'chase.com',
 'adobe.com',
 '163.com',
 '360.com',
 'haosou.com',
 'google.com.pk',
 'google.co.th',
 'google.com.eg',
 'google.com.ar',
 'youku.com',
 'google.com.sa',
 'bbc.com',
 'flipkart.com',
 'alipay.com',
 'bongacams.com',
 'adf.ly',
 'nytimes.com',
 'google.nl',
 'sogou.com',
 'livedoor.jp',
 'daum.net',
 'txxx.com',
 'amazon.cn',
 'espn.go.com',
 'ebay.co.uk',
 'ettoday.net',
 'bankofamerica.com',
 'china.com',
 'indiatimes.com',
 'myway.com',
 'bilibili.com',
 'walmart.com',
 'ebay.de',
 'china.com.cn',
 'godaddy.com',
 'dailymail.co.uk',
 'buzzfeed.com',
 'zillow.com',
 'xnxx.com',
 'salesforce.com',
 'dailymotion.com',
 'wellsfargo.com',
 'detail.tmall.com',
 'steampowered.com',
 'steamcommunity.com',
 'nametests.com',
 'google.co.ve',
 'theguardian.com',
 'google.com.ua',
 'indeed.com',
 'ameblo.jp',
 'aol.com',
 'etsy.com',
 'globo.com',
 'google.co.za',
 'yelp.com',
 'amazonaws.com',
 'huffingtonpost.com',
 'tudou.com',
 'so.com',
 'zhihu.com',
 'soundcloud.com',
 'tripadvisor.com',
 'google.gr',
 'varzesh3.com',
 'avito.ru',
 'onlinesbi.com',
 'vice.com',
 'cnzz.com',
 'directrev.com',
 'uol.com.br',
 'bet365.com',
 'weather.com',
 'mediafire.com',
 'uptodown.com',
 'cnet.com',
 'washingtonpost.com',
 'gfycat.com',
 'goo.ne.jp',
 'stackexchange.com',
 'force.com',
 'taboola.com',
 'google.com.co',
 'dmm.co.jp',
 'tuberel.com',
 'vimeo.com',
 'google.com.ng',
 'naver.jp',
 'feedly.com',
 'theladbible.com',
 'pixiv.net',
 'redtube.com',
 'detik.com',
 'homedepot.com',
 'torrentz.eu',
 'slideshare.net',
 'google.ro',
 'taringa.net',
 'foxnews.com',
 'target.com',
 'amazon.it',
 'google.com.pe',
 'flickr.com',
 'hclips.com',
 'google.be',
 'amazon.fr',
 '9gag.com',
 'kakaku.com',
 'blogspot.in',
 'ikea.com',
 'mega.nz',
 'ifeng.com',
 'udn.com',
 'web.de',
 'americanexpress.com',
 'iqiyi.com',
 'bp.blogspot.com',
 'fbcdn.net',
 'google.com.ph',
 'orange.fr',
 'comcast.net',
 'google.com.sg',
 'terraclicks.com',
 'youm7.com',
 'putlocker.is',
 'tribunnews.com',
 'gmx.net',
 'youporn.com',
 'deviantart.com',
 'nih.gov',
 'zol.com.cn',
 'ontests.me',
 'roblox.com',
 'doubleclick.net',
 'hdfcbank.com',
 'ozock.com',
 'tistory.com',
 'capitalone.com',
 'leboncoin.fr',
 'douyu.com',
 'google.cn',
 '51.la',
 'google.se',
 'spotify.com',
 'wikihow.com',
 'onet.pl',
 'babytree.com',
 'w3schools.com',
 'upornia.com',
 'snapdeal.com',
 'forbes.com',
 'google.at',
 'wix.com',
 'bestbuy.com',
 'livejournal.com',
 'mozilla.org',
 'rdsa2013.com',
 'xfinity.com',
 'handycafe.com',
 'groupon.com',
 'adnetworkperformance.com',
 'onedio.com',
 'thepiratebay.org',
 'skype.com',
 'github.io',
 'allegro.pl',
 'google.dz',
 'google.com.vn',
 'paytm.com',
 'twimg.com',
 'wikimedia.org',
 'icicibank.com',
 't-online.de',
 'tokopedia.com',
 'popcash.net',
 'telegraph.co.uk',
 'usps.com',
 'slither.io',
 'wp.pl',
 'blog.jp',
 'google.ch',
 'webtretho.com',
 'irctc.co.in',
 'trello.com',
 'google.pt',
 'yesky.com',
 'xywy.com',
 'huanqiu.com',
 'eksisozluk.com',
 'blastingnews.com',
 'citi.com',
 'shutterstock.com',
 'rediff.com',
 'files.wordpress.com',
 'ups.com',
 '1688.com',
 'google.cl',
 'bitauto.com',
 'speedtest.net',
 'pandora.com',
 'adexc.net',
 'imzog.com',
 'google.ae',
 '2ch.net',
 'google.cz',
 'loading-delivery2.com',
 'seznam.cz',
 'ltn.com.tw',
 'about.com',
 'chaturbate.com',
 'ebay-kleinanzeigen.de',
 'slack.com',
 'mercadolivre.com.br',
 'google.co.il',
 'doorblog.jp',
 'goodreads.com',
 'livejasmin.com',
 'battle.net',
 'softonic.com',
 'accuweather.com',
 'amazon.es',
 'wordpress.org',
 'mbc.net',
 'slickdeals.net',
 'icloud.com',
 'caijing.com.cn',
 'google.hu',
 'kaskus.co.id',
 'wittyfeed.com',
 'fedex.com',
 'ndtv.com',
 'att.com',
 'mlb.com',
 'kompas.com',
 'google.ie',
 'giphy.com',
 'usatoday.com',
 'xcar.com.cn',
 'hulu.com',
 'archive.org',
 'sberbank.ru',
 'media.tumblr.com',
 'pinimg.com',
 'messenger.com',
 'sourceforge.net',
 'oracle.com',
 'hp.com',
 'lowes.com',
 'zendesk.com',
 'viralthread.com',
 'csdn.net',
 '1905.com',
 'mama.cn',
 'youtube-mp3.org',
 '39.net',
 'digikala.com',
 'badoo.com',
 'businessinsider.com',
 'kinogo.co',
 'weebly.com',
 'samsung.com',
 'abs-cbn.com',
 'reimageplus.com',
 'airbnb.com',
 'sabah.com.tr',
 'wordreference.com',
 'hurriyet.com.tr',
 'uefa.com',
 'rambler.ru',
 '51yes.com',
 'cnnic.cn',
 'webmd.com',
 'ign.com',
 'liputan6.com',
 'dell.com',
 'gizmodo.com',
 'blogspot.com.br',
 'bloomberg.com',
 'blkget.com',
 'gsmarena.com',
 'evernote.com',
 'verizonwireless.com',
 'secureserver.net',
 'repubblica.it',
 'milliyet.com.tr',
 'isanalyze.com',
 'sharepoint.com',
 'eastday.com',
 'mailchimp.com',
 'nyaa.se',
 'enet.com.cn',
 'medium.com',
 'google.az',
 'akamaihd.net',
 'dmm.com',
 'billdesk.com',
 'wsj.com',
 'naukri.com',
 'kinopoisk.ru',
 'friv.com',
 'expedia.com',
 'livedoor.biz',
 'macys.com',
 'avg.com',
 'tube8.com',
 'libero.it',
 'intuit.com',
 'google.no',
 'google.fi',
 'urdupoint.com',
 'taleo.net',
 'addthis.com',
 'sahibinden.com',
 'ancestry.com',
 'likes.com',
 'savefrom.net',
 'haber7.com',
 'answers.com',
 'google.sk',
 'kissanime.to',
 'marca.com',
 'k618.cn',
 'ebay.in',
 'ask.fm',
 'wetransfer.com',
 'adplxmd.com',
 'spiegel.de',
 'bild.de',
 'livedoor.com',
 'ouo.io',
 'nownews.com',
 'elpais.com',
 'thesaurus.com',
 'rt.com',
 'amazon.ca',
 'gearbest.com',
 'ck101.com',
 'independent.co.uk',
 'reuters.com',
 'google.dk',
 'suning.com',
 'daikynguyenvn.com',
 'scribd.com',
 'themeforest.net',
 'lifebuzz.com',
 'acfun.tv',
 'box.com',
 'newegg.com',
 'nbcnews.com',
 'rutracker.org',
 'freepik.com',
 'telegram.org',
 'kapanlagi.com',
 'goal.com',
 'blogfa.com',
 'southwest.com',
 'openload.co',
 'hm.com',
 'kickstarter.com',
 'cloudfront.net',
 'thesportbible.com',
 'engadget.com',
 'impress.co.jp',
 'kohls.com',
 'playstation.com',
 'clickadu.com',
 'shopify.com',
 'tabelog.com',
 'mashable.com',
 'upwork.com',
 'espncricinfo.com',
 'conservativetribune.com',
 'siteadvisor.com',
 'realtor.com',
 'asos.com',
 'ci123.com',
 'hatena.ne.jp',
 'usaa.com',
 'xe.com',
 'olx.pl',
 'videomega.tv',
 'ameba.jp',
 'atlassian.net',
 'sh.st',
 'ebay.it',
 'doublepimp.com',
 'costco.com',
 'albawabhnews.com',
 'hatenablog.com',
 'gismeteo.ru',
 'souq.com',
 'google.by',
 'extratorrent.cc',
 'yallakora.com',
 'abcnews.go.com',
 'baike.com',
 'moneycontrol.com',
 'lifehacker.com',
 'wunderground.com',
 'hotels.com',
 'zippyshare.com',
 'zoho.com',
 'discovercard.com',
 'fidelity.com',
 'cnblogs.com',
 'zomato.com',
 'jabong.com',
 'blogimg.jp',
 'nikkei.com',
 '4shared.com',
 'offerhaus.link',
 'hespress.com',
 'theverge.com',
 'exoclick.com',
 'bhaskar.com',
 'gamer.com.tw',
 'webex.com',
 '17ok.com',
 'elmogaz.com',
 'gap.com',
 'gamepedia.com',
 'gamersky.com',
 'okezone.com',
 'gamefaqs.com',
 'infusionsoft.com',
 'ebay.com.au',
 'clipconverter.cc',
 'umblr.com',
 'ibm.com',
 'ticketmaster.com',
 'mercadolibre.com.ar',
 'beeg.com',
 'behance.net',
 'surveymonkey.com',
 'rbc.ru',
 'rednet.cn',
 'ca.gov',
 'trulia.com',
 'zing.vn',
 'elmundo.es',
 'mi.com',
 'aparat.com',
 'free.fr',
 'airtel.in',
 'blackboard.com',
 'meetup.com',
 'trackingclick.net',
 'google.bg',
 'google.lk',
 'adidas.tmall.com',
 'nordstrom.com',
 'merdeka.com',
 'list-manage.com',
 'nike.com',
 'list.tmall.com',
 'seesaa.net',
 'blogspot.jp',
 'allrecipes.com',
 'google.kz',
 'huaban.com',
 'nifty.com',
 'fiverr.com',
 'donga.com',
 'mobile.de',
 'npr.org',
 'kooora.com',
 'wayfair.com',
 'coursera.org',
 'redirectvoluum.com',
 'tutorialspoint.com',
 'panda.tv',
 'lenta.ru',
 'weblio.jp',
 'xda-developers.com',
 'asahi.com',
 'google.com.kw',
 'thefreedictionary.com',
 'adp.com',
 'kayak.com',
 'yandex.ua',
 'kijiji.ca',
 'youdao.com',
 'korabia.com',
 'chaoshi.tmall.com',
 'netteller.com',
 'drudgereport.com',
 'japanpost.jp',
 'hotstar.com',
 'tradeadexchange.com',
 'hdzog.com',
 'change.org',
 'hootsuite.com',
 'dictionary.com',
 'makemytrip.com',
 'sq.cn',
 'streamcloud.eu',
 'norton.com',
 'blog.me',
 'watsons.tmall.com',
 'prothom-alo.com',
 'researchgate.net',
 'ebates.com',
 'hotmovs.com',
 'olx.in',
 'sakura.ne.jp',
 'bookmyshow.com',
 'subscene.com',
 'le.com',
 'emol.com',
 'justdial.com',
 '11st.co.kr',
 'cookpad.com',
 'retailmenot.com',
 'thewatchseries.to',
 'alicdn.com',
 'shaparak.ir',
 'corriere.it',
 'gmarket.co.kr',
 'overstock.com',
 'asus.com',
 'y8.com',
 'yaolan.com',
 'momoshop.com.tw',
 'woot.com',
 'shopclues.com',
 'csgolounge.com',
 'disqus.com',
 'so-net.ne.jp',
 'wattpad.com',
 'ytimg.com',
 'cbsnews.com',
 'leagueoflegends.com',
 'prjcq.com',
 'reddituploads.com',
 'patch.com',
 '4399.com',
 'adbooth.com',
 'sabq.org',
 'dropbooks.tv',
 'www.gov.uk',
 'udemy.com',
 'cnmo.com',
 'bleacherreport.com',
 'aa.com',
 'lapatilla.com',
 'instructables.com',
 'clien.net',
 'bidverdrd.com',
 'nba.com',
 'mirror.co.uk',
 'interia.pl',
 'nhk.or.jp',
 'ensonhaber.com',
 'yadi.sk',
 'line.me',
 'mercadolibre.com.ve',
 'e-hentai.org',
 'uploaded.net',
 'verizon.com',
 'alexa.cn',
 'namu.wiki',
 'yodobashi.com',
 'heroquizz.com',
 'latimes.com',
 '123cha.com',
 'pof.com',
 'eyny.com',
 'azlyrics.com',
 'aliyun.com',
 'people.com',
 'yandex.com.tr',
 'rottentomatoes.com',
 '104.com.tw',
 'houzz.com',
 'time.com',
 'cisco.com',
 'ppomppu.co.kr',
 'delta.com',
 'biglobe.ne.jp',
 'jrj.com.cn',
 'xunlei.com',
 'lenovo.com',
 'usbank.com',
 'vk.me',
 'zulily.com',
 'asana.com',
 'youboy.com',
 'zone-telechargement.com',
 'glassdoor.com',
 'seasonvar.ru',
 'nikkeibp.co.jp',
 'investing.com',
 'google.com.do',
 'united.com',
 'teepr.com',
 'indianexpress.com',
 'wikiwiki.jp',
 'pch.com',
 'jimdo.com',
 'oeeee.com',
 'gyazo.com',
 'myfitnesspal.com',
 'yts.ag',
 'custhelp.com',
 'paytm.in',
 'nextdoor.com',
 'voc.com.cn',
 'cnbc.com',
 'sears.com',
 'bs.to',
 'itmedia.co.jp',
 'thekitchn.com',
 'bomb01.com',
 'slate.com',
 'torcache.net',
 'google.com.my',
 '4chan.org',
 'biobiochile.cl',
 'google.co.nz',
 'okcupid.com',
 'google.rs',
 'instructure.com',
 'intoday.in',
 'zhanqi.tv',
 'chinaso.com',
 'squarespace.com',
 'fitbit.com',
 'photobucket.com',
 'eskimi.com',
 'mixi.jp',
 '4dsply.com',
 'thatviralfeed.com',
 'pantip.com',
 'as.com',
 'elfagr.org',
 '3dmgame.com',
 'howtogeek.com',
 'aastocks.com',
 'manoramaonline.com',
 'alwafd.org',
 'inquirer.net',
 'himado.in',
 'xbox.com',
 'meaww.com',
 'pogo.com',
 'redfin.com',
 'buy.tmall.com',
 'drom.ru',
 'infoseek.co.jp',
 'buzzfil.net',
 'urbandictionary.com',
 'mit.edu',
 'olx.com.br',
 'chinaz.com',
 'chip.de',
 'panet.co.il',
 'gamespot.com',
 'google.com.ec',
 'subito.it',
 'gazetaexpress.com',
 'zara.com',
 'swagbucks.com',
 'tmz.com',
 'nexusmods.com',
 'tsite.jp',
 'timeanddate.com',
 'discuss.com.hk',
 'quanjing.com',
 'bhphotovideo.com',
 'lequipe.fr',
 'superuser.com',
 'ero-advertising.com',
 'myntra.com',
 'cdiscount.com',
 'issuu.com',
 'filehippo.com',
 'vporn.com',
 'quikr.com',
 'axisbank.co.in',
 'gameforge.com',
 'twoo.com',
 '4pda.ru',
 'java.com',
 'blogspot.mx',
 'spankbang.com',
 'discover.com',
 'kdnet.net',
 'agar.io',
 'priceline.com',
 'mercadolibre.com.mx',
 'atwiki.jp',
 'audible.com',
 'mynavi.jp',
 'vodlocker.com',
 'sky.com',
 'sciencedirect.com',
 'gigazine.net',
 'olx.ua',
 'livescore.com',
 '58.com',
 'syosetu.com',
 'prezi.com',
 'hotnewhiphop.com',
 'jcpenney.com',
 'ero-video.net',
 'nypost.com',
 'nydailynews.com',
 'acunn.com',
 'foodnetwork.com',
 'mint.com',
 'bitbucket.org',
 'creditkarma.com',
 'mataharimall.com',
 'rarbg.to',
 'tim.it',
 'anitube.se',
 'mapquest.com',
 'westernjournalism.com',
 'eventbrite.com',
 'liveinternet.ru',
 'politico.com',
 'android.com',
 'weather.gov',
 'lun.com',
 'bankmellat.ir',
 'sfgate.com',
 'misrjournal.com',
 'lemonde.fr',
 'uber.com',
 'givemesport.com',
 'stockstar.com',
 'wiktionary.org',
 '51sole.com',
 'google.hr',
 'reverso.net',
 'thehindu.com',
 'marriott.com',
 'yomiuri.co.jp',
 'topix.com',
 'prpops.com',
 'sankei.com',
 'europa.eu',
 'pcmag.com',
 'constantcontact.com',
 'battlefield.com',
 'php.net',
 'ria.ru',
 'fanpage.gr',
 'getpocket.com',
 'cpasbien.cm',
 'diep.io',
 'rightmove.co.uk',
 'sfr.fr',
 'hilton.com',
 'sozcu.com.tr',
 'blog-newstime.com',
 'agoda.com',
 'india.com',
 'bodybuilding.com',
 'techcrunch.com',
 'thisav.com',
 'hbogo.com',
 'zappos.com',
 'google.lt',
 'appledaily.com.tw',
 'geocities.jp',
 'duckduckgo.com',
 'irs.gov',
 'kotaku.com',
 'marktplaats.nl',
 'eroterest.net',
 'duolingo.com',
 'ebay.fr',
 'wp.com',
 'jin115.com',
 'staples.com',
 'youjizz.com',
 'fanfiction.net',
 'walgreens.com',
 'bt.com',
 'microsoftstore.com',
 '123movies.to',
 '126.com',
 'exblog.jp',
 'yjc.ir',
 't-mobile.com',
 'farsnews.com',
 'chron.com',
 'stumbleupon.com',
 'parentanswercentre.com',
 '123rf.com',
 'breitbart.com',
 'hh.ru',
 'cbssports.com',
 'sex.com',
 'pnc.com',
 'mega.co.nz',
 'lazada.co.id',
 'marketwatch.com',
 'ew.com',
 'ryanair.com',
 'gazeta.pl',
 'gmanetwork.com',
 'dcinside.com',
 'ampclicks.com',
 'slimspots.com',
 'basecamp.com',
 'cctv.com',
 'incometaxindiaefiling.gov.in',
 'citibank.co.in',
 'brightonclick.com',
 'gazzetta.it',
 'indianrail.gov.in',
 'idnes.cz',
 'thedailybeast.com',
 'intel.com',
 'auction.co.kr',
 'fatosdesconhecidos.com.br',
 'to8to.com',
 'ultimate-guitar.com',
 'mcafee.com',
 'neobux.com',
 'tripadvisor.co.uk',
 'tomshardware.com',
 'rapidgator.net',
 'bola.net',
 'hubspot.com',
 'otto.de',
 'digitaltrends.com',
 'elevenia.co.id',
 'n121adserv.com',
 'gofundme.com',
 'lacaixa.es',
 'ctrip.com',
 'flashx.tv',
 'quizlet.com',
 'banggood.com',
 'garmin.com',
 'primewire.ag',
 'vox.com',
 'labanquepostale.fr',
 'telekom.com',
 'drive2.ru',
 'eonline.com',
 'chosun.com',
 'credit-agricole.fr',
 'wowhead.com',
 'match.com',
 'hamariweb.com',
 'vnexpress.net',
 'familydoctor.com.cn',
 'thethao247.vn',
 'state.gov',
 'todayhumor.co.kr',
 'abril.com.br',
 'uzone.id',
 'hepsiburada.com',
 'wwwpromoter.com',
 'popsugar.com',
 'panasonic.jp',
 '360doc.com',
 'minecraft.net',
 'internethaber.com',
 'dailypakistan.com.pk',
 'bedbathandbeyond.com',
 'pixabay.com',
 'wav.tv',
 'novinky.cz',
 'uptobox.com',
 'whitepages.com',
 'icolor.com.cn',
 'babycenter.com',
 'qvc.com',
 'indiamart.com',
 'onlinecreditcenter6.com',
 '6pm.com',
 'g2a.com',
 'milanuncios.com',
 'mayoclinic.org',
 'commentcamarche.net',
 'gawker.com',
 'fandango.com',
 'duowan.com',
 'myanimelist.net',
 'telegram.me',
 'genius.com',
 'wiley.com',
 'liveleak.com',
 'divar.ir',
 'bestadbid.com',
 'niuche.com',
 'chouftv.ma',
 'life.tw',
 'dream.co.id',
 'cocolog-nifty.com',
 'ptt.cc',
 'legacy.com',
 'mynet.com']

In [100]:
rec=[]
for website in web:
    start=tm.time()
    try:
        ip = sc.gethostbyname(website.strip())
        time=tm.time()-start
    except sc.gaierror:
        ip = "No Resopnse"
        time = None
    try:
        url = "https://" + website
        response = requests.get(url, timeout=10)
        content_type = response.headers.get("Content-Type", "")
        server = response.headers.get("Server", "")
        soup = BeautifulSoup(response.text, "html.parser")
        title = soup.title.string.strip() if soup.title else None
        meta_desc = soup.find("meta", attrs={"name": "description"})
        meta_desc = meta_desc["content"].strip() if meta_desc else None
        rec.append([
            website, ip, time, content_type, server, title, meta_desc
        ])
        print(website, ip, time, content_type, server, title, meta_desc)
    except Exception as e:
        rec.append([website, ip, time, None, None, None, None, None, str(e)])
rec

youtube.com 172.217.24.174 0.010003089904785156 text/html; charset=utf-8 ESF YouTube Enjoy the videos and music that you love, upload original content and share it all with friends, family and the world on YouTube.
facebook.com 157.240.1.35 0.014770269393920898 text/html; charset="utf-8"  Facebook - लॉग इन या साइन अप करें अपने दोस्तों, परिवार और परिचित लोगों से शेयर करना और कनेक्ट करना शुरू करने के लिए Facebook में लॉग इन करें.
yahoo.com 98.137.11.163 0.01321721076965332 text/html ATS None None
amazon.com 98.87.170.74 0.014595985412597656 text/html Server Sorry! Something went wrong! None

C:\Users\hp\AppData\Local\Temp\ipykernel_22280\83068173.py:15: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(response.text, "html.parser")

wikipedia.org 103.102.166.224 0.00977468490600586 text/plain HAProxy None None
google.co.in 172.217.24.3 0.010022401809692383 text/html; charset=ISO-8859-1 gws Google None
twitter.com 162.159.140.229 0.02559638023376465 text/html; charset=utf-8 cloudflare tsa_b None None
live.com 204.79.197.212 0.00968623161315918 text/html Microsoft-HTTPAPI/2.0 Outlook None
taobao.com 59.82.43.238 0.019074201583862305 text/html; charset=utf-8 Tengine 淘宝 淘宝网 - 亚洲较大的网上交易平台，提供各类服饰、美容、家居、数码、话费/点卡充值… 数亿优质商品，同时提供担保交易(先收货后付款)等安全交易保障服务，并由商家提供退货承诺、破损补寄等消费者保障服务，让你安心享受网上购物乐趣！
bing.com 150.171.28.10 0.009117364883422852 text/html; charset=utf-8  Search - Microsoft Bing Search with Microsoft Bing and use the power of AI to find information, explore webpages, images, videos, maps, and more. A smart search engine for the forever curious.
google.co.jp 142.250.77.99 0.010739326477050781 text/html; charset=ISO-8859-1 gws Google None
msn.com 204.79.197.219 0.0008404254913330078 text/html; charset=utf-8 Kestrel MSN None
yahoo.co.jp 182.22.16.251 0.012347936630249023 text/html; charset=UTF-8 nginx Yahoo! JAPAN あなたの毎日をアップデートする情報ポータル。検索、ニュース、天気、スポーツ、メール、ショッピング、オークションなど便利なサービスを展開しています。
linkedin.com 150.171.22.12 0.0435636043548584 text/html; charset=utf-8  LinkedIn: Log In or Sign Up 1 billion members | Manage your professional identity. Build and engage with your professional network. Access knowledge, insights and opportunities.
instagram.com 157.240.1.174 0.1217644214630127 text/html; charset="utf-8"  Instagram Create an account or log in to Instagram - Share what you're into with the people who get you.
yandex.ru 77.88.55.88 0.0002865791320800781 text/html; charset=utf-8  None None
google.de 142.250.77.131 0.01647663116455078 text/html; charset=ISO-8859-1 gws Google None
google.ru 142.251.222.195 0.009206533432006836 text/html; charset=ISO-8859-1 gws Google None
ebay.com 23.58.144.150 0.020677566528320312 text/html; charset=utf-8 ebay-proxy-server Electronics, Cars, Fashion, Collectibles & More | eBay Buy & sell electronics, cars, clothes, collectibles & more on eBay, the world's online marketplace. Top brands, low prices & free shipping on many items.
reddit.com 151.101.129.140 0.10935688018798828 text/html; charset=utf-8 snooserv Reddit - The heart of the internet Reddit is where millions of people gather for conversations about the things they care about, in over 100,000 subreddit communities.
google.co.uk 142.251.223.227 0.11761856079101562 text/html; charset=ISO-8859-1 gws Google None
google.com.br 142.251.43.227 0.012456893920898438 text/html; charset=ISO-8859-1 gws Google None
t.co 172.66.0.227 0.01389932632446289 text/html; charset=utf-8 cloudflare tsa_b t.co / Twitter None
pinterest.com 151.101.0.84 0.0224301815032959 text/html; charset=utf-8  Pinterest Discover recipes, home ideas, style inspiration and other ideas to try.
amazon.co.jp 18.246.99.104 0.010892152786254883 text/html;charset=UTF-8 Server Amazon | 本, ファッション, 家電から食品まで | アマゾン Amazon.co.jp 公式サイト。アマゾンで本, 日用品, ファッション, 食品, ベビー用品, カー用品ほか一億種の商品をいつでもお安く。通常配送無料(一部を除く)
google.fr 142.250.205.99 0.023519515991210938 text/html; charset=ISO-8859-1 gws Google None
netflix.com 54.74.73.31 0.011530399322509766 text/html; charset=utf-8 envoy Netflix India – Watch TV Shows Online, Watch Movies Online Watch Netflix movies & TV shows online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more.
gmw.cn 47.93.60.29 0.03078150749206543 text/html nginx åæç½_æ°é»è§éãæåè§è§ãææ³æ·±åº¦ãçè®ºé«åº¦ åæç½æ¯åææ¥æ¥å¨ç½ç»æ¶ä»£çæ°å»¶ä¼¸ï¼ä¹æ¯å½åå¯ä¸ä¸å®¶å®ä½äºææ³çè®ºé¢åçä¸­å¤®éç¹æ°é»ç½ç«ãåæç½åæâå¯è¯»ãå¯ä¿¡ãå¯ç¨âçåç½ååï¼ä»¥âæ°é»è§éãæåè§è§ãææ³æ·±åº¦ãçè®ºé«åº¦âä¸ºçå¿µï¼åªåæé âç¥è¯åå­ç½ä¸ç²¾ç¥å®¶å­ï¼æå¨ææ³çè®ºæåç½ç«âã
tmall.com 59.82.44.54 0.023532867431640625 text/html; charset=utf-8 Tengine 天猫Tmall.com - 买正品上天猫就购了 天猫商城是一个购物平台，更是一种生活方式。天猫凭借丰富的家电、手机、电脑、服装、居家、母婴、美妆、个护、食品等众多商品种类及包含众多品牌官方旗舰店、优质的服务和便捷的购物体验，成为了消费者心中信赖的综合性购物商城。
360.cn 36.99.171.154 0.09355711936950684 text/html nginx 360å®ç½ -360å®å¨ä¸­å¿ - 360å®å¨è½¯ä»¶ - 360æºè½ç¡¬ä»¶ - 360æºè½å®¶å± - 360ä¼ä¸æå¡ None
google.it 142.251.220.99 0.010683774948120117 text/html; charset=ISO-8859-1 gws Google None
microsoft.com 13.107.213.58 0.00037980079650878906 text/html AkamaiNetStorage Your request has been blocked. This could be
                        due to several reasons. None
onclickads.net 139.45.197.105 0.1159508228302002 text/html nginx 404 Not Found None
google.es 142.251.220.99 0.009587764739990234 text/html; charset=ISO-8859-1 gws Google None
paypal.com 151.101.3.1 0.009905099868774414 text/html; charset=utf-8  PayPal Account | Mobile Wallet and More | PayPal IN Use your PayPal account to spend, send, and manage your money. Or, create a merchant account for your business. And so much more. Discover the details here.
sohu.com 61.135.164.50 0.07768058776855469  D0 None None
wordpress.com 192.0.78.9 0.010706186294555664 text/html; charset=utf-8 nginx WordPress.com: Everything You Need to Build Your Website Create your WordPress website with built-in hosting, premium themes, and powerful tools. No technical setup required. Start building today—free plan available.
tumblr.com 192.0.77.40 0.11110091209411621 text/html; charset=utf-8 nginx Trending topics on Tumblr Explore trending topics on Tumblr. See all of the GIFs, fan art, and general conversation about the internet’s favorite things.
blogspot.com 142.250.77.137 0.009391069412231445 text/html sffe Blogger.com - Create a unique and beautiful blog easily. Publish your passions your way. Whether youâd like to share your knowledge, experiences or the latest news, create a unique and beautiful blog.
imgur.com 199.232.196.193 0.00034618377685546875 application/json cat factory 1.0 None None
google.com.mx 172.217.24.163 0.013436555862426758 text/html; charset=ISO-8859-1 gws Google None
naver.com 223.130.192.248 0.09004831314086914 text/html; charset=UTF-8 nfront NAVER 네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요
stackoverflow.com 104.18.32.7 0.009994745254516602 text/html; charset=utf-8 cloudflare Newest Questions - Stack Overflow None
apple.com 17.253.144.10 0.01946854591369629 text/html; charset=utf-8 Apple Apple None
chinadaily.com.cn 111.13.49.147 0.0002968311309814453 text/html;charset=UTF-8 nginx China Daily Website - Connecting China Connecting the World Chinadaily.com.cn is the largest English portal in China, providing news, business information, BBS, learning materials. The Website has channels as China, BizChina, World, Opinion, Sports/Olympics, Entertainment, Lifestyle, Culture, Citylife, Photo, Forum and Weather.
fc2.com 199.48.210.152 0.1104576587677002 text/html nginx FC2 - Free Website, Analyzer, Blog, Rental Server, SEO Countermeasures, etc. - FC2 is a portal site which brings you a pleasant web life providing blog/website/analyzer services and others. Our blog service is ranked No.2 domestically and supported by wide range of users including both beginners and heavy users. We offer as many as 30 different services.
imdb.com 52.94.237.74 0.10344147682189941 text/html Server 403 Forbidden None
google.ca 142.250.183.163 0.010580062866210938 text/html; charset=ISO-8859-1 gws Google None
google.co.kr 142.250.183.131 0.009072542190551758 text/html; charset=ISO-8859-1 gws Google None
github.com 20.207.73.82 0.00044536590576171875 text/html; charset=utf-8 github.com GitHub · Build and ship software on a single, collaborative platform · GitHub Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity.
google.com.hk 142.251.221.99 0.011405706405639648 text/html; charset=UTF-8 gws Google None
whatsapp.com 157.240.23.53 0.0003514289855957031 text/html; charset="utf-8"  WhatsApp | Secure and Reliable Free Private Messaging and Calling Use WhatsApp Messenger to stay in touch with friends and family. WhatsApp is free and offers simple, secure, reliable messaging and calling, available on phones all over the world.
diply.com 104.26.2.12 0.1188054084777832 text/html; charset=UTF-8 cloudflare Diply – Get Lost Somewhere Good… <?php echo get_the_excerpt(); ?>
jd.com 111.13.149.108 0.018731117248535156 text/html nginx äº¬ä¸å¨çç-ä¸ä¸çç»¼åç½ä¸è´­ç©åå äº¬ä¸å¨çç-ä¸ä¸çç»¼åç½ä¸è´­ç©ååï¼ä¸ºæ¨æä¾æ­£åä½ä»·çè´­ç©éæ©ãä¼è´¨ä¾¿æ·çæå¡ä½éªãååæ¥èªå¨çæ°åä¸åçåå®¶ï¼åæ¬å®¶çµãææºãè®¡ç®æºãæè£ãå±å®¶ãæ¯å©´ãç¾å¦ãä¸ªæ¤ãé£åç­ä¸°å¯åç±»ï¼æ»¡è¶³åç§è´­ç©éæ±ãé¦æ¸¯çç¨æ·æ¯æèªæãäº¬ä¸éè¿åå½éå¡æ¯ä»ï¼ç°æ¶å·²è¦çé¦æ¸¯ãæ¾³é¨ãå°æ¹¾ãæ°å å¡ãé©¬æ¥è¥¿äºãç¾å½ãå æ¿å¤§ãæ¾³å¤§å©äºãæ°è¥¿å°åæ¥æ¬ç­æµ·å¤200å¤ä¸ªå½å®¶åå°åºã
amazon.de 3.253.171.165 0.01254725456237793 text/html Server Amazon.de None
google.com.tr 142.250.205.99 0.01076364517211914 text/html; charset=ISO-8859-1 gws Google None
rakuten.co.jp 133.237.180.69 0.010039091110229492 text/html; charset=UTF-8 Apache 【楽天市場】Shopping is Entertainment! ： インターネット最大級の通信販売、通販オンラインショッピングコミュニティ 楽天市場はインターネット通販が楽しめる総合ショッピングモール。楽天ポイントがどんどん貯まる！使える！毎日お得なクーポンも。食品から家電、ファッション、ベビー用品、コスメまで、充実の品揃え。
craigslist.org 208.82.237.129 0.029973983764648438 text/html; charset=UTF-8  craigslist: bangladesh jobs, apartments, for sale, services, community, and events craigslist provides local classifieds and forums for jobs, housing, for sale, services, local community, and events
office.com 13.107.6.156 0.018183469772338867 text/html; charset=utf-8  Login | Microsoft 365 Copilot Collaborate for free with online versions of Microsoft Word, PowerPoint, Excel, and OneNote. Save documents, workbooks, and presentations online, in OneDrive. Share them with others and work together at the same time.
google.co.id 142.251.221.99 0.019321441650390625 text/html; charset=ISO-8859-1 gws Google None
amazon.in 3.253.168.43 0.00031065940856933594 text/html Server 503 - Service Unavailable Error None
blogger.com 142.251.221.169 0.01599574089050293 text/html sffe Blogger.com - Create a unique and beautiful blog easily. Publish your passions your way. Whether youâd like to share your knowledge, experiences or the latest news, create a unique and beautiful blog.
google.pl 142.250.77.99 0.009392023086547852 text/html; charset=ISO-8859-1 gws Google None
nicovideo.jp 18.164.144.129 0.010185480117797852 text/html; charset=UTF-8 Apache ニコニコ 日本最大級の動画サービス、ニコニコ（niconico）。動画にコメントを付けて楽しむニコニコ動画や、生放送番組にリアルタイムでコメントを付けられるニコニコ生放送のほか、イラスト・マンガ・最新ニュース・ゲームなど、エンターテイメントを全て無料で楽しめる！
alibaba.com 47.246.131.198 0.018573999404907227 text/html;charset=UTF-8  Alibaba.com: Manufacturers, Suppliers, Exporters & Importers from the world's largest online B2B marketplace Find quality Manufacturers, Suppliers, Exporters, Importers, Buyers, Wholesalers, Products and Trade Leads from our award-winning International Trade Site. Import & Export on alibaba.com
soso.com 43.153.236.147 0.012514352798461914 text/html nginx æææ´æä½ None
pixnet.net 103.23.108.107 0.0940854549407959 text/html; charset=utf-8  痞客邦PIXNET-掌握最新熱門話題貼文、短影音，讓生活充滿靈感! 痞客邦提供部落格、短貼文、短影音等自媒體網路平台服務，匯集最新活動資訊熱搜話題，涵蓋美食、旅遊、親子、影視、美妝等文章，快來一起分享更多生活靈感與挑戰吧！
google.com.au 142.250.66.3 0.11576318740844727 text/html; charset=ISO-8859-1 gws Google None
go.com 13.248.150.189 0.009987831115722656 text/html; charset=utf-8 nginx Go.com | The Walt Disney Company Go.com is the top-level home on the Internet to the online properties of The Walt Disney Company.
amazon.co.uk 3.253.181.192 0.07605218887329102 text/html Server Amazon.co.uk None
dropbox.com 162.125.248.18 0.10237693786621094 text/html; charset=utf-8 envoy Dropbox.com Discover Dropbox – secure, easy cloud storage for file sharing and collaboration. With Dash, save time and organize all your company content in one place.
google.com.tw 142.250.67.35 0.01842355728149414 text/html; charset=ISO-8859-1 gws Google None
outbrain.com 151.101.66.132 0.014196634292602539 text/html; charset=utf-8  Outbrain Direct Response to Maximize Your ROI Drive elevated outcomes and monetize your content with Outbrain Direct Response
cntv.cn 138.113.157.172 0.011694908142089844 text/html CCTVAMCLOUD å¤®è§ç½_ä¸çå°±å¨ç¼å å¤®è§ç½ï¼www.cctv.comï¼ç±ä¸­å¤®å¹¿æ­çµè§æ»å°ä¸»åï¼æ¯ä»¥è§é¢ä¸ºç¹è²çä¸­å¤®éç¹æ°é»ç½ç«ï¼æ¯å¤®è§çèåä¼ æ­å¹³å°ï¼æ¯æ¥æå¨çç§ä¸å¡èµè´¨çå¤§åäºèç½æåä¼ä¸ãç§æ¿âèååæ°ãä¸ä½åå±âççå¿µï¼ä»¥æ°é»ä¸ºé¾å¤´ï¼ä»¥è§é¢ä¸ºéç¹ï¼ä»¥ç¨æ·ä¸ºä¸­å¿ï¼å»ºæâä¸ç½ä¸ç«¯å¤å¹³å°å¤æ¸ éâèåªä½ä¼ æ­ä½ç³»ã
googleusercontent.com 142.250.77.97 0.02162647247314453 text/html; charset=UTF-8 sffe Error 404 (Not Found)!!1 None
cnn.com 151.101.131.5 0.0008347034454345703 text/html; charset=utf-8  Breaking News, Latest News and Videos | CNN View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN.com.
ask.com 151.101.158.114 0.017634153366088867 text/html; charset=UTF-8  Ask.com - What's Your Question? Answers you want. Content for days. What more could you Ask for?
coccoc.com 123.30.175.29 0.01017618179321289 text/html; charset=utf-8 nginx Trình duyệt Cốc Cốc | Trình duyệt web dành cho người Việt Trình duyệt web Cốc Cốc chặn quảng cáo hiệu quả, tải nhạc, video dễ dàng, ghim video trên mọi nền tảng. Tải ngay cho Windows, Mac, iOS và Android.
booking.com 13.35.20.122 0.009411811828613281 text/html; charset=UTF-8 nginx Booking.com | Official site | The best hotels, flights, car rentals & accommodations Explore the world with Booking.com. Big savings on homes, hotels, flights, car rentals, taxis, and attractions – build your perfect trip on any budget.
bbc.co.uk 151.101.64.81 0.11062908172607422 text/html BBC-GTM BBC - Home The best of the BBC, with the latest news and sport headlines, weather, TV & radio highlights and much more from across the whole of BBC Online.
popads.net 216.21.13.12 0.0007145404815673828 text/html  PopAds - Home Simply the best popunder adnetwork in the industry - try and check yourself!
youth.cn 163.171.124.28 0.010360240936279297 text/html nginx ÖÐ¹úÇàÄêÍø_ÇàÄêÎÂ¶È¡¢Çà´ºö¦¶È¡¢ÇàÍøÌ¬¶È ÖÐ¹úÇàÄêÍø£¬1999Äê5ÔÂ4ÈÕÕýÊ½¿ªÍ¨£¬¹²ÇàÍÅÖÐÑëÖ÷°ìµÄÖÐÑëÖØµãÐÂÎÅÍøÕ¾£¬ÊÇ¹úÄÚ×î´óµÄÇàÄêÖ÷Á÷ÍøÕ¾¡£ÖÐ¹úÇàÄêÍø½ß³Ï·þÎñÇàÄêµÄÎÄ»¯¡¢ÐÄÀí¡¢Çé¸ÐºÍ´´ÒµÐèÇó£¬ÊÇ¹²ÇàÍÅÔËÓÃÍøÂçÎÄ»¯ÔªËØÎüÒýÇàÄêµÄÐÂÔØÌåºÍÒýµ¼ÇàÄêµÄÐÂÍ¾¾¶£¬ÎªÍÅ×éÖ¯Í¨¹ýÐÂÃ½ÌåÈÚÈëÇàÄêÌá¹©ÓÐÁ¦Ö§³Å¡£ ÖÐ¹úÇàÄêÍøÓµÓÐ400Óà¸ö×ÓÍøÕ¾£¬2000¶à¸öÀ¸Ä¿£¬ÓÃÎÄ×Ö¡¢Í¼Æ¬¡¢¶¯Âþ¡¢ÒôÊÓÆµ¡¢ÂÛÌ³¡¢²©¿Í¡¢Î¢²©¡¢ÊÖ»ú¡¢ÍøÉÏÖ±²¥µÈ¶àÖÖÊÖ¶Î£¬ÒÀÍÐ¹²ÇàÍÅÖÐÑë·á¸»µÄ×ÊÔ´£¬Ã¿ÌìÏòÈ«ÇòÍøÃñ·¢²¼·á¸»¶à²ÊµÄÐÅÏ¢£¬ÄÚÈÝ°üÀ¨ÕþÖÎ¡¢¾­¼Ã¡¢Éç»á¡¢ÎÄ»¯¡¢ÓéÀÖ¡¢Ê±ÉÐ¡¢½ÌÓý¡¢ÐÄÀíµÈ¸÷¸öÁìÓò¡£
twitch.tv 151.101.130.167 0.10771894454956055 text/html  Twitch Twitch is an interactive livestreaming service for content spanning gaming, entertainment, sports, music, and more.
wikia.com 151.101.192.194 0.010339736938476562 text/html; charset=UTF-8 envoy Explore | Fandom None
quora.com 3.229.20.136 0.08661270141601562 text/html; charset=UTF-8 cloudflare Just a moment... None
chase.com 146.143.83.57 0.010331153869628906 text/html; charset=utf-8  Credit Card, Mortgage, Banking, Auto | Chase Online | Chase.com Chase online; credit cards, mortgages, commercial banking, auto loans, investing & retirement planning, checking and business banking.
adobe.com 23.58.95.17 0.09701895713806152 text/html AkamaiNetStorage None None
360.com 104.192.110.232 0.02003026008605957 text/html; charset=utf-8 nginx 360官网 -360安全中心 - 360安全软件 - 360智能硬件 - 360智能家居 - 360企业服务 None
haosou.com 104.192.110.226 0.018723726272583008 text/html; charset=UTF-8 openresty/1.15.8.3 360搜索，SO靠谱 360搜索是安全、精准、可信赖的新一代搜索引擎，依托于360母品牌的安全优势，全面拦截各类钓鱼欺诈等恶意网站，提供更放心的搜索服务。 360搜索 so靠谱。
google.com.pk 142.251.43.131 0.054456472396850586 text/html; charset=ISO-8859-1 gws Google None
google.co.th 142.250.77.131 0.012173175811767578 text/html; charset=ISO-8859-1 gws Google None
google.com.eg 142.251.43.131 0.021791934967041016 text/html; charset=ISO-8859-1 gws Google None
google.com.ar 142.251.221.99 0.014588356018066406 text/html; charset=ISO-8859-1 gws Google None
google.com.sa 142.251.220.99 0.10266470909118652 text/html; charset=ISO-8859-1 gws Google None
bbc.com 151.101.64.81 0.012373685836791992 text/html; charset=utf-8 BBC-GTM BBC Home - Breaking News, World News, US News, Sports, Business, Innovation, Climate, Culture, Travel, Video & Audio Visit BBC for trusted reporting on the latest world and US news, sports, business, climate, innovation, culture and much more.
bongacams.com 195.85.23.88 0.010348081588745117 text/html; charset=UTF-8 cloudflare Just a moment... None
adf.ly 172.66.43.117 0.01106119155883789 text/html; charset=UTF-8 cloudflare Attention Required! | Cloudflare None
nytimes.com 151.101.1.164 0.0941469669342041 text/html; charset=utf-8 envoy The New York Times - Breaking News, US News, World News and Videos Live news, investigations, opinion, photos and video by the journalists of The New York Times from more than 150 countries around the world. Subscribe for coverage of U.S. and international news, politics, business, technology, science, health, arts, sports and more.
google.nl 142.251.222.163 0.0187985897064209 text/html; charset=ISO-8859-1 gws Google None
daum.net 211.249.220.24 0.010323047637939453 text/html  Daum ì´ì©ì ì íê¶ì ê°íí ë´ì¤, ì¸ìì ëª¨ë  ì ë³´ë¥¼ ì°ê²°íë ê²ì. Daumìì ëì ê´ì¬ ì½íì¸ ë¥¼ ì¦ê²¨ë³´ì¸ì.
amazon.cn 54.222.60.218 0.1260206699371338 text/html Server æµ·å¤è´­æ¹çéç¥ None
espn.go.com 18.67.233.37 0.02184152603149414 text/html CloudFront ERROR: The request could not be satisfied None
ebay.co.uk 23.202.229.140 0.016953706741333008 text/html;charset=UTF-8 ebay-proxy-server eBay UK | Electronics, Cars, Fashion, Collectibles & More Buy & sell electronics, cars, clothes, collectibles & more on eBay UK's online marketplace. Top brands, low prices & free shipping on many items.
ettoday.net 219.85.79.131 0.8601493835449219 text/html; charset=utf-8 nginx ETtoday新聞雲 | Today is my day 《ETtoday新聞雲》由東森集團總裁王令麟所創辦，於2011年11月開站，新聞、影音、節目、直播、社群、個人化服務，及App都深獲網友喜愛，在台灣網路觸及率超過8成，多項評比是新聞網站第一名；在全世界各地華人亦頗受歡迎，全球擁有2000萬粉絲。除了線上數位廣告外，我們也提供線下廣告刊登服務《ETtoday家外媒體》，包含台北捷運廣告刊登(燈箱廣告、壁貼廣告...等)、微風南京建築外牆廣告、建北/建南LED等戶外媒體代理。
indiatimes.com 23.58.62.151 0.11347103118896484 text/html; charset=utf-8 Bhoot Indiatimes: Latest in Lifestyle, Health, Fashion, and Wellness Indiatimes is your destination when it comes to exploring the latest in lifestyle trends, health and wellness hacks, and fashion advice. From food fads to travel tips and relationship rules, we tell you how to live your best life. Bookmark this for all the latest lifestyle content tailored just for you.
myway.com 151.101.158.114 0.010439872741699219 text/html; charset=utf-8  www.myway.com None
bilibili.com 8.134.50.24 0.01191401481628418 text/html openresty åºéå¦! - bilibili.com None
walmart.com 23.200.56.195 0.021588802337646484 text/html; charset=utf-8  Robot or human? None
ebay.de 23.58.144.150 0.01833200454711914 text/html;charset=UTF-8 ebay-proxy-server eBay.de | Elektronik, Autos, Mode, Sammlerstücke, Möbel und mehr Online-Shopping Kaufen und verkaufen Sie Elektronikartikel, Autos, Kleidung, Mode, Sammlerstücke, Sportartikel, Digitalkameras, Babyartikel, Gutscheine und vieles mehr bei eBay.de, dem weltweiten Online-Marktplatz.
godaddy.com 198.71.249.70 0.011366844177246094 text/html AkamaiGHost Access Denied None
buzzfeed.com 151.101.130.114 0.019237756729125977 text/html; charset=utf-8 nginx BuzzFeed BuzzFeed has breaking news, vital journalism, quizzes, videos, celeb news, Tasty food videos, recipes, DIY hacks, and all the trending buzz you’ll want to share with your friends. Copyright BuzzFeed, Inc. All rights reserved.

[[' google.com',
  '142.251.223.14',
  0.08590817451477051,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'%20google.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B499D590>: Failed to resolve \'%20google.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['youtube.com',
  '172.217.24.174',
  0.010003089904785156,
  'text/html; charset=utf-8',
  'ESF',
  'YouTube',
  'Enjoy the videos and music that you love, upload original content and share it all with friends, family and the world on YouTube.'],
 ['facebook.com',
  '157.240.1.35',
  0.014770269393920898,
  'text/html; charset="utf-8"',
  '',
  'Facebook - लॉग इन या साइन अप करें',
  'अपने दोस्तों, परिवार और परिचित लोगों से शेयर करना और कनेक्ट करना शुरू करने के लिए Facebook में लॉग इन करें.'],
 ['baidu.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'baidu.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B6B69810>: Failed to resolve \'baidu.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['yahoo.com',
  '98.137.11.163',
  0.01321721076965332,
  'text/html',
  'ATS',
  None,
  None],
 ['amazon.com',
  '98.87.170.74',
  0.014595985412597656,
  'text/html',
  'Server',
  'Sorry! Something went wrong!',
  None],
 ['wikipedia.org',
  '103.102.166.224',
  0.00977468490600586,
  'text/plain',
  'HAProxy',
  None,
  None],
 ['google.co.in',
  '172.217.24.3',
  0.010022401809692383,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['twitter.com',
  '162.159.140.229',
  0.02559638023376465,
  'text/html; charset=utf-8',
  'cloudflare tsa_b',
  None,
  None],
 ['qq.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'qq.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B6B68050>: Failed to resolve \'qq.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['live.com',
  '204.79.197.212',
  0.00968623161315918,
  'text/html',
  'Microsoft-HTTPAPI/2.0',
  'Outlook',
  None],
 ['taobao.com',
  '59.82.43.238',
  0.019074201583862305,
  'text/html; charset=utf-8',
  'Tengine',
  '淘宝',
  '淘宝网 - 亚洲较大的网上交易平台，提供各类服饰、美容、家居、数码、话费/点卡充值… 数亿优质商品，同时提供担保交易(先收货后付款)等安全交易保障服务，并由商家提供退货承诺、破损补寄等消费者保障服务，让你安心享受网上购物乐趣！'],
 ['bing.com',
  '150.171.28.10',
  0.009117364883422852,
  'text/html; charset=utf-8',
  '',
  'Search - Microsoft Bing',
  'Search with Microsoft Bing and use the power of AI to find information, explore webpages, images, videos, maps, and more. A smart search engine for the forever curious.'],
 ['google.co.jp',
  '142.250.77.99',
  0.010739326477050781,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['msn.com',
  '204.79.197.219',
  0.0008404254913330078,
  'text/html; charset=utf-8',
  'Kestrel',
  'MSN',
  None],
 ['yahoo.co.jp',
  '182.22.16.251',
  0.012347936630249023,
  'text/html; charset=UTF-8',
  'nginx',
  'Yahoo! JAPAN',
  'あなたの毎日をアップデートする情報ポータル。検索、ニュース、天気、スポーツ、メール、ショッピング、オークションなど便利なサービスを展開しています。'],
 ['linkedin.com',
  '150.171.22.12',
  0.0435636043548584,
  'text/html; charset=utf-8',
  '',
  'LinkedIn: Log In or Sign Up',
  '1 billion members | Manage your professional identity. Build and engage with your professional network. Access knowledge, insights and opportunities.'],
 ['sina.com.cn',
  '36.51.254.91',
  0.10892057418823242,
  None,
  None,
  None,
  None,
  None,
  "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"],
 ['instagram.com',
  '157.240.1.174',
  0.1217644214630127,
  'text/html; charset="utf-8"',
  '',
  'Instagram',
  "Create an account or log in to Instagram - Share what you're into with the people who get you."],
 ['weibo.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'weibo.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B499FED0>: Failed to resolve \'weibo.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['vk.com',
  '87.240.132.72',
  0.009746074676513672,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'m.vk.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B6B68050>: Failed to resolve \'m.vk.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['yandex.ru',
  '77.88.55.88',
  0.0002865791320800781,
  'text/html; charset=utf-8',
  '',
  None,
  None],
 ['google.de',
  '142.250.77.131',
  0.01647663116455078,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['google.ru',
  '142.251.222.195',
  0.009206533432006836,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['hao123.com',
  '124.237.176.248',
  0.010079383850097656,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'hao123.com\', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for \'hao123.com\'. (_ssl.c:1028)")))'],
 ['ebay.com',
  '23.58.144.150',
  0.020677566528320312,
  'text/html; charset=utf-8',
  'ebay-proxy-server',
  'Electronics, Cars, Fashion, Collectibles & More | eBay',
  "Buy & sell electronics, cars, clothes, collectibles & more on eBay, the world's online marketplace. Top brands, low prices & free shipping on many items."],
 ['reddit.com',
  '151.101.129.140',
  0.10935688018798828,
  'text/html; charset=utf-8',
  'snooserv',
  'Reddit - The heart of the internet',
  'Reddit is where millions of people gather for conversations about the things they care about, in over 100,000 subreddit communities.'],
 ['google.co.uk',
  '142.251.223.227',
  0.11761856079101562,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['google.com.br',
  '142.251.43.227',
  0.012456893920898438,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['mail.ru',
  '89.221.239.1',
  0.009624242782592773,
  None,
  None,
  None,
  None,
  None,
  "'NoneType' object has no attribute 'strip'"],
 ['t.co',
  '172.66.0.227',
  0.01389932632446289,
  'text/html; charset=utf-8',
  'cloudflare tsa_b',
  't.co / Twitter',
  None],
 ['pinterest.com',
  '151.101.0.84',
  0.0224301815032959,
  'text/html; charset=utf-8',
  '',
  'Pinterest',
  'Discover recipes, home ideas, style inspiration and other ideas to try.'],
 ['amazon.co.jp',
  '18.246.99.104',
  0.010892152786254883,
  'text/html;charset=UTF-8',
  'Server',
  'Amazon | 本, ファッション, 家電から食品まで | アマゾン',
  'Amazon.co.jp 公式サイト。アマゾンで本, 日用品, ファッション, 食品, ベビー用品, カー用品ほか一億種の商品をいつでもお安く。通常配送無料(一部を除く)'],
 ['google.fr',
  '142.250.205.99',
  0.023519515991210938,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['netflix.com',
  '54.74.73.31',
  0.011530399322509766,
  'text/html; charset=utf-8',
  'envoy',
  'Netflix India – Watch TV Shows Online, Watch Movies Online',
  'Watch Netflix movies & TV shows online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more.'],
 ['gmw.cn',
  '47.93.60.29',
  0.03078150749206543,
  'text/html',
  'nginx',
  'å\x85\x89æ\x98\x8eç½\x91_æ\x96°é\x97»è§\x86é\x87\x8eã\x80\x81æ\x96\x87å\x8c\x96è§\x86è§\x92ã\x80\x81æ\x80\x9dæ\x83³æ·±åº¦ã\x80\x81ç\x90\x86è®ºé«\x98åº¦',
  'å\x85\x89æ\x98\x8eç½\x91æ\x98¯å\x85\x89æ\x98\x8eæ\x97¥æ\x8a¥å\x9c¨ç½\x91ç»\x9cæ\x97¶ä»£ç\x9a\x84æ\x96°å»¶ä¼¸ï¼\x8cä¹\x9fæ\x98¯å\x9b½å\x86\x85å\x94¯ä¸\x80ä¸\x80å®¶å®\x9aä½\x8däº\x8eæ\x80\x9dæ\x83³ç\x90\x86è®ºé¢\x86å\x9f\x9fç\x9a\x84ä¸\xadå¤®é\x87\x8dç\x82¹æ\x96°é\x97»ç½\x91ç«\x99ã\x80\x82å\x85\x89æ\x98\x8eç½\x91å\x9d\x9aæ\x8c\x81â\x80\x9cå\x8f¯è¯»ã\x80\x81å\x8f¯ä¿¡ã\x80\x81å\x8f¯ç\x94¨â\x80\x9dç\x9a\x84å\x8a\x9eç½\x91å\x8e\x9få\x88\x99ï¼\x8cä»¥â\x80\x9cæ\x96°é\x97»è§\x86é\x87\x8eã\x80\x81æ\x96\x87å\x8c\x96è§\x86è§\x92ã\x80\x81æ\x80\x9dæ\x83³æ·±åº¦ã\x80\x81ç\x90\x86è®ºé«\x98åº¦â\x80\x9dä¸ºç\x90\x86å¿µï¼\x8cå\x8aªå\x8a\x9bæ\x89\x93é\x80\xa0â\x80\x9cç\x9f¥è¯\x86å\x88\x86å\xad\x90ç½\x91ä¸\x8aç²¾ç¥\x9eå®¶å\x9b\xadï¼\x8cæ\x9d\x83å¨\x81æ\x80\x9dæ\x83³ç\x90\x86è®ºæ\x96\x87å\x8c\x96ç½\x91ç«\x99â\x80\x9dã\x80\x82'],
 ['tmall.com',
  '59.82.44.54',
  0.023532867431640625,
  'text/html; charset=utf-8',
  'Tengine',
  '天猫Tmall.com - 买正品上天猫就购了',
  '天猫商城是一个购物平台，更是一种生活方式。天猫凭借丰富的家电、手机、电脑、服装、居家、母婴、美妆、个护、食品等众多商品种类及包含众多品牌官方旗舰店、优质的服务和便捷的购物体验，成为了消费者心中信赖的综合性购物商城。'],
 ['360.cn',
  '36.99.171.154',
  0.09355711936950684,
  'text/html',
  'nginx',
  '360å®\x98ç½\x91 -360å®\x89å\x85¨ä¸\xadå¿\x83 - 360å®\x89å\x85¨è½¯ä»¶ - 360æ\x99ºè\x83½ç¡¬ä»¶ - 360æ\x99ºè\x83½å®¶å±\x85 - 360ä¼\x81ä¸\x9aæ\x9c\x8då\x8a¡',
  None],
 ['google.it',
  '142.251.220.99',
  0.010683774948120117,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['microsoft.com',
  '13.107.213.58',
  0.00037980079650878906,
  'text/html',
  'AkamaiNetStorage',
  'Your request has been blocked. This could be\r\n                        due to several reasons.',
  None],
 ['onclickads.net',
  '139.45.197.105',
  0.1159508228302002,
  'text/html',
  'nginx',
  '404 Not Found',
  None],
 ['google.es',
  '142.251.220.99',
  0.009587764739990234,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['paypal.com',
  '151.101.3.1',
  0.009905099868774414,
  'text/html; charset=utf-8',
  '',
  'PayPal Account | Mobile Wallet and More | PayPal IN',
  'Use your PayPal account to spend, send, and manage your money. Or, create a merchant account for your business. And so much more. Discover the details here.'],
 ['sohu.com', '61.135.164.50', 0.07768058776855469, '', 'D0', None, None],
 ['wordpress.com',
  '192.0.78.9',
  0.010706186294555664,
  'text/html; charset=utf-8',
  'nginx',
  'WordPress.com: Everything You Need to Build Your Website',
  'Create your WordPress website with built-in hosting, premium themes, and powerful tools. No technical setup required. Start building today—free plan available.'],
 ['tumblr.com',
  '192.0.77.40',
  0.11110091209411621,
  'text/html; charset=utf-8',
  'nginx',
  'Trending topics on Tumblr',
  'Explore trending topics on Tumblr. See all of the GIFs, fan art, and general conversation about the internet’s favorite things.'],
 ['blogspot.com',
  '142.250.77.137',
  0.009391069412231445,
  'text/html',
  'sffe',
  'Blogger.com - Create a unique and beautiful blog easily.',
  'Publish your passions your way. Whether youâ\x80\x99d like to share your knowledge, experiences or the latest news, create a unique and beautiful blog.'],
 ['imgur.com',
  '199.232.196.193',
  0.00034618377685546875,
  'application/json',
  'cat factory 1.0',
  None,
  None],
 ['xvideos.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'xvideos.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B5241950>: Failed to resolve \'xvideos.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['google.com.mx',
  '172.217.24.163',
  0.013436555862426758,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['naver.com',
  '223.130.192.248',
  0.09004831314086914,
  'text/html; charset=UTF-8',
  'nfront',
  'NAVER',
  '네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요'],
 ['stackoverflow.com',
  '104.18.32.7',
  0.009994745254516602,
  'text/html; charset=utf-8',
  'cloudflare',
  'Newest Questions - Stack Overflow',
  None],
 ['apple.com',
  '17.253.144.10',
  0.01946854591369629,
  'text/html; charset=utf-8',
  'Apple',
  'Apple',
  None],
 ['chinadaily.com.cn',
  '111.13.49.147',
  0.0002968311309814453,
  'text/html;charset=UTF-8',
  'nginx',
  'China Daily Website - Connecting China Connecting the World',
  'Chinadaily.com.cn is the largest English portal in China, providing news, business information, BBS, learning materials. The Website has channels as China, BizChina, World, Opinion, Sports/Olympics, Entertainment, Lifestyle, Culture, Citylife, Photo, Forum and Weather.'],
 ['fc2.com',
  '199.48.210.152',
  0.1104576587677002,
  'text/html',
  'nginx',
  'FC2 - Free Website, Analyzer, Blog, Rental Server, SEO Countermeasures, etc. -',
  'FC2 is a portal site which brings you a pleasant web life providing blog/website/analyzer services and others. Our blog service is ranked No.2 domestically and supported by wide range of users including both beginners and heavy users. We offer as many as 30 different services.'],
 ['aliexpress.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'aliexpress.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B8958F50>: Failed to resolve \'aliexpress.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['imdb.com',
  '52.94.237.74',
  0.10344147682189941,
  'text/html',
  'Server',
  '403 Forbidden',
  None],
 ['google.ca',
  '142.250.183.163',
  0.010580062866210938,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['google.co.kr',
  '142.250.183.131',
  0.009072542190551758,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['github.com',
  '20.207.73.82',
  0.00044536590576171875,
  'text/html; charset=utf-8',
  'github.com',
  'GitHub · Build and ship software on a single, collaborative platform · GitHub',
  "Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity."],
 ['ok.ru',
  '5.61.23.11',
  0.026552200317382812,
  None,
  None,
  None,
  None,
  None,
  "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"],
 ['pornhub.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'pornhub.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B5241950>: Failed to resolve \'pornhub.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['google.com.hk',
  '142.251.221.99',
  0.011405706405639648,
  'text/html; charset=UTF-8',
  'gws',
  'Google',
  None],
 ['whatsapp.com',
  '157.240.23.53',
  0.0003514289855957031,
  'text/html; charset="utf-8"',
  '',
  'WhatsApp | Secure and Reliable Free Private Messaging and Calling',
  'Use WhatsApp Messenger to stay in touch with friends and family. WhatsApp is free and offers simple, secure, reliable messaging and calling, available on phones all over the world.'],
 ['diply.com',
  '104.26.2.12',
  0.1188054084777832,
  'text/html; charset=UTF-8',
  'cloudflare',
  'Diply – Get Lost Somewhere Good…',
  '<?php echo get_the_excerpt(); ?>'],
 ['jd.com',
  '111.13.149.108',
  0.018731117248535156,
  'text/html',
  'nginx',
  'äº¬ä¸\x9cå\x85¨ç\x90\x83ç\x89\x88-ä¸\x93ä¸\x9aç\x9a\x84ç»¼å\x90\x88ç½\x91ä¸\x8aè´\xadç\x89©å\x95\x86å\x9f\x8e',
  'äº¬ä¸\x9cå\x85¨ç\x90\x83ç\x89\x88-ä¸\x93ä¸\x9aç\x9a\x84ç»¼å\x90\x88ç½\x91ä¸\x8aè´\xadç\x89©å\x95\x86å\x9f\x8eï¼\x8cä¸ºæ\x82¨æ\x8f\x90ä¾\x9bæ\xad£å\x93\x81ä½\x8eä»·ç\x9a\x84è´\xadç\x89©é\x80\x89æ\x8b©ã\x80\x81ä¼\x98è´¨ä¾¿æ\x8d·ç\x9a\x84æ\x9c\x8då\x8a¡ä½\x93éª\x8cã\x80\x82å\x95\x86å\x93\x81æ\x9d¥è\x87ªå\x85¨ç\x90\x83æ\x95°å\x8d\x81ä¸\x87å\x93\x81ç\x89\x8cå\x95\x86å®¶ï¼\x8cå\x9b\x8aæ\x8b¬å®¶ç\x94µã\x80\x81æ\x89\x8bæ\x9cºã\x80\x81è®¡ç®\x97æ\x9cºã\x80\x81æ\x9c\x8dè£\x85ã\x80\x81å±\x85å®¶ã\x80\x81æ¯\x8då©´ã\x80\x81ç¾\x8eå¦\x86ã\x80\x81ä¸ªæ\x8a¤ã\x80\x81é£\x9få\x93\x81ç\xad\x89ä¸°å¯\x8cå\x93\x81ç±»ï¼\x8cæ»¡è¶³å\x90\x84ç§\x8dè´\xadç\x89©é\x9c\x80æ±\x82ã\x80\x82é¦\x99æ¸¯ç\x9a\x84ç\x94¨æ\x88·æ\x94¯æ\x8c\x81è\x87ªæ\x8f\x90ã\x80\x81äº¬ä¸\x9cé\x9b\x86è¿\x90å\x92\x8cå\x9b½é\x99\x85å\x8d¡æ\x94¯ä»\x98ï¼\x8cç\x8e°æ\x97¶å·²è¦\x86ç\x9b\x96é¦\x99æ¸¯ã\x80\x81æ¾³é\x97¨ã\x80\x81å\x8f°æ¹¾ã\x80\x81æ\x96°å\x8a\xa0å\x9d¡ã\x80\x81é©¬æ\x9d¥è¥¿äº\x9aã\x80\x81ç¾\x8eå\x9b½ã\x80\x81å\x8a\xa0æ\x8b¿å¤§ã\x80\x81æ¾³å¤§å\x88©äº\x9aã\x80\x81æ\x96°è¥¿å\x85°å\x92\x8cæ\x97¥æ\x9c¬ç\xad\x89æµ·å¤\x96200å¤\x9aä¸ªå\x9b½å®¶å\x92\x8cå\x9c°å\x8cºã\x80\x82'],
 ['amazon.de',
  '3.253.171.165',
  0.01254725456237793,
  'text/html',
  'Server',
  'Amazon.de',
  None],
 ['google.com.tr',
  '142.250.205.99',
  0.01076364517211914,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['rakuten.co.jp',
  '133.237.180.69',
  0.010039091110229492,
  'text/html; charset=UTF-8',
  'Apache',
  '【楽天市場】Shopping is Entertainment! ： インターネット最大級の通信販売、通販オンラインショッピングコミュニティ',
  '楽天市場はインターネット通販が楽しめる総合ショッピングモール。楽天ポイントがどんどん貯まる！使える！毎日お得なクーポンも。食品から家電、ファッション、ベビー用品、コスメまで、充実の品揃え。'],
 ['craigslist.org',
  '208.82.237.129',
  0.029973983764648438,
  'text/html; charset=UTF-8',
  '',
  'craigslist: bangladesh jobs, apartments, for sale, services, community, and events',
  'craigslist provides local classifieds and forums for jobs, housing, for sale, services, local community, and events'],
 ['office.com',
  '13.107.6.156',
  0.018183469772338867,
  'text/html; charset=utf-8',
  '',
  'Login | Microsoft 365 Copilot',
  'Collaborate for free with online versions of Microsoft Word, PowerPoint, Excel, and OneNote. Save documents, workbooks, and presentations online, in OneDrive. Share them with others and work together at the same time.'],
 ['google.co.id',
  '142.251.221.99',
  0.019321441650390625,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['kat.cr',
  '185.53.177.53',
  0.012591838836669922,
  None,
  None,
  None,
  None,
  None,
  "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"],
 ['amazon.in',
  '3.253.168.43',
  0.00031065940856933594,
  'text/html',
  'Server',
  '503 - Service Unavailable Error',
  None],
 ['tianya.cn',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'tianya.cn\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B8669A90>: Failed to resolve \'tianya.cn\' ([Errno 11002] getaddrinfo failed)"))'],
 ['blogger.com',
  '142.251.221.169',
  0.01599574089050293,
  'text/html',
  'sffe',
  'Blogger.com - Create a unique and beautiful blog easily.',
  'Publish your passions your way. Whether youâ\x80\x99d like to share your knowledge, experiences or the latest news, create a unique and beautiful blog.'],
 ['google.pl',
  '142.250.77.99',
  0.009392023086547852,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['nicovideo.jp',
  '18.164.144.129',
  0.010185480117797852,
  'text/html; charset=UTF-8',
  'Apache',
  'ニコニコ',
  '日本最大級の動画サービス、ニコニコ（niconico）。動画にコメントを付けて楽しむニコニコ動画や、生放送番組にリアルタイムでコメントを付けられるニコニコ生放送のほか、イラスト・マンガ・最新ニュース・ゲームなど、エンターテイメントを全て無料で楽しめる！'],
 ['alibaba.com',
  '47.246.131.198',
  0.018573999404907227,
  'text/html;charset=UTF-8',
  '',
  "Alibaba.com: Manufacturers, Suppliers, Exporters & Importers from the world's largest online B2B marketplace",
  'Find quality Manufacturers, Suppliers, Exporters, Importers, Buyers, Wholesalers, Products and Trade Leads from our award-winning International Trade Site. Import & Export on alibaba.com'],
 ['soso.com',
  '43.153.236.147',
  0.012514352798461914,
  'text/html',
  'nginx',
  'æ\x90\x9cæ\x90\x9cæ\x9b´æ\x87\x82ä½',
  None],
 ['pixnet.net',
  '103.23.108.107',
  0.0940854549407959,
  'text/html; charset=utf-8',
  '',
  '痞客邦PIXNET-掌握最新熱門話題貼文、短影音，讓生活充滿靈感!',
  '痞客邦提供部落格、短貼文、短影音等自媒體網路平台服務，匯集最新活動資訊熱搜話題，涵蓋美食、旅遊、親子、影視、美妝等文章，快來一起分享更多生活靈感與挑戰吧！'],
 ['google.com.au',
  '142.250.66.3',
  0.11576318740844727,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['go.com',
  '13.248.150.189',
  0.009987831115722656,

In [101]:
rec

[[' google.com',
  '142.251.223.14',
  0.08590817451477051,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'%20google.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B499D590>: Failed to resolve \'%20google.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['youtube.com',
  '172.217.24.174',
  0.010003089904785156,
  'text/html; charset=utf-8',
  'ESF',
  'YouTube',
  'Enjoy the videos and music that you love, upload original content and share it all with friends, family and the world on YouTube.'],
 ['facebook.com',
  '157.240.1.35',
  0.014770269393920898,
  'text/html; charset="utf-8"',
  '',
  'Facebook - लॉग इन या साइन अप करें',
  'अपने दोस्तों, परिवार और परिचित लोगों से शेयर करना और कनेक्ट करना शुरू करने के लिए Facebook में लॉग इन करें.'],
 ['baidu.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'baidu.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B6B69810>: Failed to resolve \'baidu.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['yahoo.com',
  '98.137.11.163',
  0.01321721076965332,
  'text/html',
  'ATS',
  None,
  None],
 ['amazon.com',
  '98.87.170.74',
  0.014595985412597656,
  'text/html',
  'Server',
  'Sorry! Something went wrong!',
  None],
 ['wikipedia.org',
  '103.102.166.224',
  0.00977468490600586,
  'text/plain',
  'HAProxy',
  None,
  None],
 ['google.co.in',
  '172.217.24.3',
  0.010022401809692383,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['twitter.com',
  '162.159.140.229',
  0.02559638023376465,
  'text/html; charset=utf-8',
  'cloudflare tsa_b',
  None,
  None],
 ['qq.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'qq.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B6B68050>: Failed to resolve \'qq.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['live.com',
  '204.79.197.212',
  0.00968623161315918,
  'text/html',
  'Microsoft-HTTPAPI/2.0',
  'Outlook',
  None],
 ['taobao.com',
  '59.82.43.238',
  0.019074201583862305,
  'text/html; charset=utf-8',
  'Tengine',
  '淘宝',
  '淘宝网 - 亚洲较大的网上交易平台，提供各类服饰、美容、家居、数码、话费/点卡充值… 数亿优质商品，同时提供担保交易(先收货后付款)等安全交易保障服务，并由商家提供退货承诺、破损补寄等消费者保障服务，让你安心享受网上购物乐趣！'],
 ['bing.com',
  '150.171.28.10',
  0.009117364883422852,
  'text/html; charset=utf-8',
  '',
  'Search - Microsoft Bing',
  'Search with Microsoft Bing and use the power of AI to find information, explore webpages, images, videos, maps, and more. A smart search engine for the forever curious.'],
 ['google.co.jp',
  '142.250.77.99',
  0.010739326477050781,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['msn.com',
  '204.79.197.219',
  0.0008404254913330078,
  'text/html; charset=utf-8',
  'Kestrel',
  'MSN',
  None],
 ['yahoo.co.jp',
  '182.22.16.251',
  0.012347936630249023,
  'text/html; charset=UTF-8',
  'nginx',
  'Yahoo! JAPAN',
  'あなたの毎日をアップデートする情報ポータル。検索、ニュース、天気、スポーツ、メール、ショッピング、オークションなど便利なサービスを展開しています。'],
 ['linkedin.com',
  '150.171.22.12',
  0.0435636043548584,
  'text/html; charset=utf-8',
  '',
  'LinkedIn: Log In or Sign Up',
  '1 billion members | Manage your professional identity. Build and engage with your professional network. Access knowledge, insights and opportunities.'],
 ['sina.com.cn',
  '36.51.254.91',
  0.10892057418823242,
  None,
  None,
  None,
  None,
  None,
  "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"],
 ['instagram.com',
  '157.240.1.174',
  0.1217644214630127,
  'text/html; charset="utf-8"',
  '',
  'Instagram',
  "Create an account or log in to Instagram - Share what you're into with the people who get you."],
 ['weibo.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'weibo.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B499FED0>: Failed to resolve \'weibo.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['vk.com',
  '87.240.132.72',
  0.009746074676513672,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'m.vk.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B6B68050>: Failed to resolve \'m.vk.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['yandex.ru',
  '77.88.55.88',
  0.0002865791320800781,
  'text/html; charset=utf-8',
  '',
  None,
  None],
 ['google.de',
  '142.250.77.131',
  0.01647663116455078,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['google.ru',
  '142.251.222.195',
  0.009206533432006836,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['hao123.com',
  '124.237.176.248',
  0.010079383850097656,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'hao123.com\', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for \'hao123.com\'. (_ssl.c:1028)")))'],
 ['ebay.com',
  '23.58.144.150',
  0.020677566528320312,
  'text/html; charset=utf-8',
  'ebay-proxy-server',
  'Electronics, Cars, Fashion, Collectibles & More | eBay',
  "Buy & sell electronics, cars, clothes, collectibles & more on eBay, the world's online marketplace. Top brands, low prices & free shipping on many items."],
 ['reddit.com',
  '151.101.129.140',
  0.10935688018798828,
  'text/html; charset=utf-8',
  'snooserv',
  'Reddit - The heart of the internet',
  'Reddit is where millions of people gather for conversations about the things they care about, in over 100,000 subreddit communities.'],
 ['google.co.uk',
  '142.251.223.227',
  0.11761856079101562,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['google.com.br',
  '142.251.43.227',
  0.012456893920898438,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['mail.ru',
  '89.221.239.1',
  0.009624242782592773,
  None,
  None,
  None,
  None,
  None,
  "'NoneType' object has no attribute 'strip'"],
 ['t.co',
  '172.66.0.227',
  0.01389932632446289,
  'text/html; charset=utf-8',
  'cloudflare tsa_b',
  't.co / Twitter',
  None],
 ['pinterest.com',
  '151.101.0.84',
  0.0224301815032959,
  'text/html; charset=utf-8',
  '',
  'Pinterest',
  'Discover recipes, home ideas, style inspiration and other ideas to try.'],
 ['amazon.co.jp',
  '18.246.99.104',
  0.010892152786254883,
  'text/html;charset=UTF-8',
  'Server',
  'Amazon | 本, ファッション, 家電から食品まで | アマゾン',
  'Amazon.co.jp 公式サイト。アマゾンで本, 日用品, ファッション, 食品, ベビー用品, カー用品ほか一億種の商品をいつでもお安く。通常配送無料(一部を除く)'],
 ['google.fr',
  '142.250.205.99',
  0.023519515991210938,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['netflix.com',
  '54.74.73.31',
  0.011530399322509766,
  'text/html; charset=utf-8',
  'envoy',
  'Netflix India – Watch TV Shows Online, Watch Movies Online',
  'Watch Netflix movies & TV shows online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more.'],
 ['gmw.cn',
  '47.93.60.29',
  0.03078150749206543,
  'text/html',
  'nginx',
  'å\x85\x89æ\x98\x8eç½\x91_æ\x96°é\x97»è§\x86é\x87\x8eã\x80\x81æ\x96\x87å\x8c\x96è§\x86è§\x92ã\x80\x81æ\x80\x9dæ\x83³æ·±åº¦ã\x80\x81ç\x90\x86è®ºé«\x98åº¦',
  'å\x85\x89æ\x98\x8eç½\x91æ\x98¯å\x85\x89æ\x98\x8eæ\x97¥æ\x8a¥å\x9c¨ç½\x91ç»\x9cæ\x97¶ä»£ç\x9a\x84æ\x96°å»¶ä¼¸ï¼\x8cä¹\x9fæ\x98¯å\x9b½å\x86\x85å\x94¯ä¸\x80ä¸\x80å®¶å®\x9aä½\x8däº\x8eæ\x80\x9dæ\x83³ç\x90\x86è®ºé¢\x86å\x9f\x9fç\x9a\x84ä¸\xadå¤®é\x87\x8dç\x82¹æ\x96°é\x97»ç½\x91ç«\x99ã\x80\x82å\x85\x89æ\x98\x8eç½\x91å\x9d\x9aæ\x8c\x81â\x80\x9cå\x8f¯è¯»ã\x80\x81å\x8f¯ä¿¡ã\x80\x81å\x8f¯ç\x94¨â\x80\x9dç\x9a\x84å\x8a\x9eç½\x91å\x8e\x9få\x88\x99ï¼\x8cä»¥â\x80\x9cæ\x96°é\x97»è§\x86é\x87\x8eã\x80\x81æ\x96\x87å\x8c\x96è§\x86è§\x92ã\x80\x81æ\x80\x9dæ\x83³æ·±åº¦ã\x80\x81ç\x90\x86è®ºé«\x98åº¦â\x80\x9dä¸ºç\x90\x86å¿µï¼\x8cå\x8aªå\x8a\x9bæ\x89\x93é\x80\xa0â\x80\x9cç\x9f¥è¯\x86å\x88\x86å\xad\x90ç½\x91ä¸\x8aç²¾ç¥\x9eå®¶å\x9b\xadï¼\x8cæ\x9d\x83å¨\x81æ\x80\x9dæ\x83³ç\x90\x86è®ºæ\x96\x87å\x8c\x96ç½\x91ç«\x99â\x80\x9dã\x80\x82'],
 ['tmall.com',
  '59.82.44.54',
  0.023532867431640625,
  'text/html; charset=utf-8',
  'Tengine',
  '天猫Tmall.com - 买正品上天猫就购了',
  '天猫商城是一个购物平台，更是一种生活方式。天猫凭借丰富的家电、手机、电脑、服装、居家、母婴、美妆、个护、食品等众多商品种类及包含众多品牌官方旗舰店、优质的服务和便捷的购物体验，成为了消费者心中信赖的综合性购物商城。'],
 ['360.cn',
  '36.99.171.154',
  0.09355711936950684,
  'text/html',
  'nginx',
  '360å®\x98ç½\x91 -360å®\x89å\x85¨ä¸\xadå¿\x83 - 360å®\x89å\x85¨è½¯ä»¶ - 360æ\x99ºè\x83½ç¡¬ä»¶ - 360æ\x99ºè\x83½å®¶å±\x85 - 360ä¼\x81ä¸\x9aæ\x9c\x8då\x8a¡',
  None],
 ['google.it',
  '142.251.220.99',
  0.010683774948120117,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['microsoft.com',
  '13.107.213.58',
  0.00037980079650878906,
  'text/html',
  'AkamaiNetStorage',
  'Your request has been blocked. This could be\r\n                        due to several reasons.',
  None],
 ['onclickads.net',
  '139.45.197.105',
  0.1159508228302002,
  'text/html',
  'nginx',
  '404 Not Found',
  None],
 ['google.es',
  '142.251.220.99',
  0.009587764739990234,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['paypal.com',
  '151.101.3.1',
  0.009905099868774414,
  'text/html; charset=utf-8',
  '',
  'PayPal Account | Mobile Wallet and More | PayPal IN',
  'Use your PayPal account to spend, send, and manage your money. Or, create a merchant account for your business. And so much more. Discover the details here.'],
 ['sohu.com', '61.135.164.50', 0.07768058776855469, '', 'D0', None, None],
 ['wordpress.com',
  '192.0.78.9',
  0.010706186294555664,
  'text/html; charset=utf-8',
  'nginx',
  'WordPress.com: Everything You Need to Build Your Website',
  'Create your WordPress website with built-in hosting, premium themes, and powerful tools. No technical setup required. Start building today—free plan available.'],
 ['tumblr.com',
  '192.0.77.40',
  0.11110091209411621,
  'text/html; charset=utf-8',
  'nginx',
  'Trending topics on Tumblr',
  'Explore trending topics on Tumblr. See all of the GIFs, fan art, and general conversation about the internet’s favorite things.'],
 ['blogspot.com',
  '142.250.77.137',
  0.009391069412231445,
  'text/html',
  'sffe',
  'Blogger.com - Create a unique and beautiful blog easily.',
  'Publish your passions your way. Whether youâ\x80\x99d like to share your knowledge, experiences or the latest news, create a unique and beautiful blog.'],
 ['imgur.com',
  '199.232.196.193',
  0.00034618377685546875,
  'application/json',
  'cat factory 1.0',
  None,
  None],
 ['xvideos.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'xvideos.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B5241950>: Failed to resolve \'xvideos.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['google.com.mx',
  '172.217.24.163',
  0.013436555862426758,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['naver.com',
  '223.130.192.248',
  0.09004831314086914,
  'text/html; charset=UTF-8',
  'nfront',
  'NAVER',
  '네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요'],
 ['stackoverflow.com',
  '104.18.32.7',
  0.009994745254516602,
  'text/html; charset=utf-8',
  'cloudflare',
  'Newest Questions - Stack Overflow',
  None],
 ['apple.com',
  '17.253.144.10',
  0.01946854591369629,
  'text/html; charset=utf-8',
  'Apple',
  'Apple',
  None],
 ['chinadaily.com.cn',
  '111.13.49.147',
  0.0002968311309814453,
  'text/html;charset=UTF-8',
  'nginx',
  'China Daily Website - Connecting China Connecting the World',
  'Chinadaily.com.cn is the largest English portal in China, providing news, business information, BBS, learning materials. The Website has channels as China, BizChina, World, Opinion, Sports/Olympics, Entertainment, Lifestyle, Culture, Citylife, Photo, Forum and Weather.'],
 ['fc2.com',
  '199.48.210.152',
  0.1104576587677002,
  'text/html',
  'nginx',
  'FC2 - Free Website, Analyzer, Blog, Rental Server, SEO Countermeasures, etc. -',
  'FC2 is a portal site which brings you a pleasant web life providing blog/website/analyzer services and others. Our blog service is ranked No.2 domestically and supported by wide range of users including both beginners and heavy users. We offer as many as 30 different services.'],
 ['aliexpress.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'aliexpress.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B8958F50>: Failed to resolve \'aliexpress.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['imdb.com',
  '52.94.237.74',
  0.10344147682189941,
  'text/html',
  'Server',
  '403 Forbidden',
  None],
 ['google.ca',
  '142.250.183.163',
  0.010580062866210938,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['google.co.kr',
  '142.250.183.131',
  0.009072542190551758,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['github.com',
  '20.207.73.82',
  0.00044536590576171875,
  'text/html; charset=utf-8',
  'github.com',
  'GitHub · Build and ship software on a single, collaborative platform · GitHub',
  "Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity."],
 ['ok.ru',
  '5.61.23.11',
  0.026552200317382812,
  None,
  None,
  None,
  None,
  None,
  "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"],
 ['pornhub.com',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'pornhub.com\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B5241950>: Failed to resolve \'pornhub.com\' ([Errno 11001] getaddrinfo failed)"))'],
 ['google.com.hk',
  '142.251.221.99',
  0.011405706405639648,
  'text/html; charset=UTF-8',
  'gws',
  'Google',
  None],
 ['whatsapp.com',
  '157.240.23.53',
  0.0003514289855957031,
  'text/html; charset="utf-8"',
  '',
  'WhatsApp | Secure and Reliable Free Private Messaging and Calling',
  'Use WhatsApp Messenger to stay in touch with friends and family. WhatsApp is free and offers simple, secure, reliable messaging and calling, available on phones all over the world.'],
 ['diply.com',
  '104.26.2.12',
  0.1188054084777832,
  'text/html; charset=UTF-8',
  'cloudflare',
  'Diply – Get Lost Somewhere Good…',
  '<?php echo get_the_excerpt(); ?>'],
 ['jd.com',
  '111.13.149.108',
  0.018731117248535156,
  'text/html',
  'nginx',
  'äº¬ä¸\x9cå\x85¨ç\x90\x83ç\x89\x88-ä¸\x93ä¸\x9aç\x9a\x84ç»¼å\x90\x88ç½\x91ä¸\x8aè´\xadç\x89©å\x95\x86å\x9f\x8e',
  'äº¬ä¸\x9cå\x85¨ç\x90\x83ç\x89\x88-ä¸\x93ä¸\x9aç\x9a\x84ç»¼å\x90\x88ç½\x91ä¸\x8aè´\xadç\x89©å\x95\x86å\x9f\x8eï¼\x8cä¸ºæ\x82¨æ\x8f\x90ä¾\x9bæ\xad£å\x93\x81ä½\x8eä»·ç\x9a\x84è´\xadç\x89©é\x80\x89æ\x8b©ã\x80\x81ä¼\x98è´¨ä¾¿æ\x8d·ç\x9a\x84æ\x9c\x8då\x8a¡ä½\x93éª\x8cã\x80\x82å\x95\x86å\x93\x81æ\x9d¥è\x87ªå\x85¨ç\x90\x83æ\x95°å\x8d\x81ä¸\x87å\x93\x81ç\x89\x8cå\x95\x86å®¶ï¼\x8cå\x9b\x8aæ\x8b¬å®¶ç\x94µã\x80\x81æ\x89\x8bæ\x9cºã\x80\x81è®¡ç®\x97æ\x9cºã\x80\x81æ\x9c\x8dè£\x85ã\x80\x81å±\x85å®¶ã\x80\x81æ¯\x8då©´ã\x80\x81ç¾\x8eå¦\x86ã\x80\x81ä¸ªæ\x8a¤ã\x80\x81é£\x9få\x93\x81ç\xad\x89ä¸°å¯\x8cå\x93\x81ç±»ï¼\x8cæ»¡è¶³å\x90\x84ç§\x8dè´\xadç\x89©é\x9c\x80æ±\x82ã\x80\x82é¦\x99æ¸¯ç\x9a\x84ç\x94¨æ\x88·æ\x94¯æ\x8c\x81è\x87ªæ\x8f\x90ã\x80\x81äº¬ä¸\x9cé\x9b\x86è¿\x90å\x92\x8cå\x9b½é\x99\x85å\x8d¡æ\x94¯ä»\x98ï¼\x8cç\x8e°æ\x97¶å·²è¦\x86ç\x9b\x96é¦\x99æ¸¯ã\x80\x81æ¾³é\x97¨ã\x80\x81å\x8f°æ¹¾ã\x80\x81æ\x96°å\x8a\xa0å\x9d¡ã\x80\x81é©¬æ\x9d¥è¥¿äº\x9aã\x80\x81ç¾\x8eå\x9b½ã\x80\x81å\x8a\xa0æ\x8b¿å¤§ã\x80\x81æ¾³å¤§å\x88©äº\x9aã\x80\x81æ\x96°è¥¿å\x85°å\x92\x8cæ\x97¥æ\x9c¬ç\xad\x89æµ·å¤\x96200å¤\x9aä¸ªå\x9b½å®¶å\x92\x8cå\x9c°å\x8cºã\x80\x82'],
 ['amazon.de',
  '3.253.171.165',
  0.01254725456237793,
  'text/html',
  'Server',
  'Amazon.de',
  None],
 ['google.com.tr',
  '142.250.205.99',
  0.01076364517211914,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['rakuten.co.jp',
  '133.237.180.69',
  0.010039091110229492,
  'text/html; charset=UTF-8',
  'Apache',
  '【楽天市場】Shopping is Entertainment! ： インターネット最大級の通信販売、通販オンラインショッピングコミュニティ',
  '楽天市場はインターネット通販が楽しめる総合ショッピングモール。楽天ポイントがどんどん貯まる！使える！毎日お得なクーポンも。食品から家電、ファッション、ベビー用品、コスメまで、充実の品揃え。'],
 ['craigslist.org',
  '208.82.237.129',
  0.029973983764648438,
  'text/html; charset=UTF-8',
  '',
  'craigslist: bangladesh jobs, apartments, for sale, services, community, and events',
  'craigslist provides local classifieds and forums for jobs, housing, for sale, services, local community, and events'],
 ['office.com',
  '13.107.6.156',
  0.018183469772338867,
  'text/html; charset=utf-8',
  '',
  'Login | Microsoft 365 Copilot',
  'Collaborate for free with online versions of Microsoft Word, PowerPoint, Excel, and OneNote. Save documents, workbooks, and presentations online, in OneDrive. Share them with others and work together at the same time.'],
 ['google.co.id',
  '142.251.221.99',
  0.019321441650390625,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['kat.cr',
  '185.53.177.53',
  0.012591838836669922,
  None,
  None,
  None,
  None,
  None,
  "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"],
 ['amazon.in',
  '3.253.168.43',
  0.00031065940856933594,
  'text/html',
  'Server',
  '503 - Service Unavailable Error',
  None],
 ['tianya.cn',
  'No Resopnse',
  None,
  None,
  None,
  None,
  None,
  None,
  'HTTPSConnectionPool(host=\'tianya.cn\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000189B8669A90>: Failed to resolve \'tianya.cn\' ([Errno 11002] getaddrinfo failed)"))'],
 ['blogger.com',
  '142.251.221.169',
  0.01599574089050293,
  'text/html',
  'sffe',
  'Blogger.com - Create a unique and beautiful blog easily.',
  'Publish your passions your way. Whether youâ\x80\x99d like to share your knowledge, experiences or the latest news, create a unique and beautiful blog.'],
 ['google.pl',
  '142.250.77.99',
  0.009392023086547852,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['nicovideo.jp',
  '18.164.144.129',
  0.010185480117797852,
  'text/html; charset=UTF-8',
  'Apache',
  'ニコニコ',
  '日本最大級の動画サービス、ニコニコ（niconico）。動画にコメントを付けて楽しむニコニコ動画や、生放送番組にリアルタイムでコメントを付けられるニコニコ生放送のほか、イラスト・マンガ・最新ニュース・ゲームなど、エンターテイメントを全て無料で楽しめる！'],
 ['alibaba.com',
  '47.246.131.198',
  0.018573999404907227,
  'text/html;charset=UTF-8',
  '',
  "Alibaba.com: Manufacturers, Suppliers, Exporters & Importers from the world's largest online B2B marketplace",
  'Find quality Manufacturers, Suppliers, Exporters, Importers, Buyers, Wholesalers, Products and Trade Leads from our award-winning International Trade Site. Import & Export on alibaba.com'],
 ['soso.com',
  '43.153.236.147',
  0.012514352798461914,
  'text/html',
  'nginx',
  'æ\x90\x9cæ\x90\x9cæ\x9b´æ\x87\x82ä½',
  None],
 ['pixnet.net',
  '103.23.108.107',
  0.0940854549407959,
  'text/html; charset=utf-8',
  '',
  '痞客邦PIXNET-掌握最新熱門話題貼文、短影音，讓生活充滿靈感!',
  '痞客邦提供部落格、短貼文、短影音等自媒體網路平台服務，匯集最新活動資訊熱搜話題，涵蓋美食、旅遊、親子、影視、美妝等文章，快來一起分享更多生活靈感與挑戰吧！'],
 ['google.com.au',
  '142.250.66.3',
  0.11576318740844727,
  'text/html; charset=ISO-8859-1',
  'gws',
  'Google',
  None],
 ['go.com',
  '13.248.150.189',
  0.009987831115722656,

In [105]:
data = pd.DataFrame(rec, columns=["Website", "IP Address","Response_Time","content_type","server","title","meta_desc","Wrong","error"])
data.head()

,Website,IP Address,Response_Time,content_type,server,title,meta_desc,Wrong,error
0,google.com,142.251.223.14,0.085908,None,None,None,None,None,"HTTPSConnectionPool(host='%20google.com', port..."
1,youtube.com,172.217.24.174,0.010003,text/html; charset=utf-8,ESF,YouTube,"Enjoy the videos and music that you love, uplo...",None,None
2,facebook.com,157.240.1.35,0.014770,"text/html; charset=""utf-8""",,Facebook - लॉग इन या साइन अप करें,"अपने दोस्तों, परिवार और परिचित लोगों से शेयर क...",None,None
3,baidu.com,No Resopnse,NaN,None,None,None,None,None,"HTTPSConnectionPool(host='baidu.com', port=443..."
4,yahoo.com,98.137.11.163,0.013217,text/html,ATS,None,None,None,None

In [106]:
data.to_csv('MetaData.csv')

In [107]:
data.to_excel("website_metadata.xlsx", index=False)

In [ ]:
import requests

In [83]:
url=web[421].strip()
url = "https://" + url
response = requests.get(url, timeout=10)

In [84]:
print(response.status_code)
print(response.headers)
print(response.text[:200])

436
{'Content-Length': '0', 'Date': 'Fri, 17 Oct 2025 12:14:54 GMT', 'Server': 'Parking/1.0'}

In [85]:
content_type = response.headers.get("Content-Type", "")
server = response.headers.get("Server", "")

In [86]:
content_type

''

In [87]:
server

'Parking/1.0'

In [88]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")
title = soup.title.string.strip() if soup.title else None
meta_desc = soup.find("meta", attrs={"name": "description"})
meta_desc = meta_desc["content"].strip() if meta_desc else None

In [89]:
print(meta_desc)

None

In [7]:
data = pd.DataFrame(rec, columns=["Website", "IP Address","Response_Time"])
data

               Website       IP Address  Response_Time
0           google.com   216.58.200.174       0.000901
1          youtube.com  142.250.182.174       0.000424
2         facebook.com      31.13.64.35       0.000331
3            baidu.com     39.156.70.37       0.107188
4            yahoo.com      74.6.231.21       0.000723
..                 ...              ...            ...
995        dream.co.id    146.190.82.73       0.262749
996  cocolog-nifty.com      No Resopnse            NaN
997             ptt.cc    140.112.172.1       0.151906
998         legacy.com     64.68.200.48       0.154486
999          mynet.com   212.101.122.34       0.011471

[1000 rows x 3 columns]

In [8]:
data[data['IP Address']=='No Resopnse']

                          Website   IP Address  Response_Time
74                      tianya.cn  No Resopnse            NaN
100           microsoftonline.com  No Resopnse            NaN
129                     china.com  No Resopnse            NaN
171                 directrev.com  No Resopnse            NaN
179                    gfycat.com  No Resopnse            NaN
189                      naver.jp  No Resopnse            NaN
218               bp.blogspot.com  No Resopnse            NaN
233                    ontests.me  No Resopnse            NaN
258                  rdsa2013.com  No Resopnse            NaN
271                     twimg.com  No Resopnse            NaN
355               youtube-mp3.org  No Resopnse            NaN
391                       nyaa.se  No Resopnse            NaN
395                  akamaihd.net  No Resopnse            NaN
425                        ask.fm  No Resopnse            NaN
437                  gearbest.com  No Resopnse            NaN
461                cloudfront.net  No Resopnse            NaN
494               extratorrent.cc  No Resopnse            NaN
509                    blogimg.jp  No Resopnse            NaN
512                offerhaus.link  No Resopnse            NaN
570            redirectvoluum.com  No Resopnse            NaN
581                     yandex.ua  No Resopnse            NaN
586                 netteller.com  No Resopnse            NaN
588                  japanpost.jp  No Resopnse            NaN
596                         sq.cn  No Resopnse            NaN
631                     ytimg.com  No Resopnse            NaN
634                     prjcq.com  No Resopnse            NaN
635             reddituploads.com  No Resopnse            NaN
653                     nhk.or.jp  No Resopnse            NaN
741                    alwafd.org  No Resopnse            NaN
743                     himado.in  No Resopnse            NaN
780                axisbank.co.in  No Resopnse            NaN
783                       4pda.ru  No Resopnse            NaN
867                  geocities.jp  No Resopnse            NaN
888                  farsnews.com  No Resopnse            NaN
891        parentanswercentre.com  No Resopnse            NaN
910  incometaxindiaefiling.gov.in  No Resopnse            NaN
932                n121adserv.com  No Resopnse            NaN
936                     flashx.tv  No Resopnse            NaN
976       onlinecreditcenter6.com  No Resopnse            NaN
991                 bestadbid.com  No Resopnse            NaN
996             cocolog-nifty.com  No Resopnse            NaN

In [9]:
data[data['IP Address']=='No Resopnse'].shape

(41, 3)

In [152]:
import numpy as np

In [154]:
data[np.isnan(data['Response_Time'])]

                          Website   IP Address  Response_Time
74                      tianya.cn  No Resopnse            NaN
100           microsoftonline.com  No Resopnse            NaN
129                     china.com  No Resopnse            NaN
171                 directrev.com  No Resopnse            NaN
179                    gfycat.com  No Resopnse            NaN
189                      naver.jp  No Resopnse            NaN
218               bp.blogspot.com  No Resopnse            NaN
233                    ontests.me  No Resopnse            NaN
237                     ozock.com  No Resopnse            NaN
258                  rdsa2013.com  No Resopnse            NaN
271                     twimg.com  No Resopnse            NaN
355               youtube-mp3.org  No Resopnse            NaN
371                     51yes.com  No Resopnse            NaN
391                       nyaa.se  No Resopnse            NaN
395                  akamaihd.net  No Resopnse            NaN
425                        ask.fm  No Resopnse            NaN
437                  gearbest.com  No Resopnse            NaN
461                cloudfront.net  No Resopnse            NaN
494               extratorrent.cc  No Resopnse            NaN
509                    blogimg.jp  No Resopnse            NaN
570            redirectvoluum.com  No Resopnse            NaN
581                     yandex.ua  No Resopnse            NaN
586                 netteller.com  No Resopnse            NaN
588                  japanpost.jp  No Resopnse            NaN
596                         sq.cn  No Resopnse            NaN
631                     ytimg.com  No Resopnse            NaN
635             reddituploads.com  No Resopnse            NaN
653                     nhk.or.jp  No Resopnse            NaN
741                    alwafd.org  No Resopnse            NaN
743                     himado.in  No Resopnse            NaN
780                axisbank.co.in  No Resopnse            NaN
783                       4pda.ru  No Resopnse            NaN
867                  geocities.jp  No Resopnse            NaN
872                 eroterest.net  No Resopnse            NaN
888                  farsnews.com  No Resopnse            NaN
891        parentanswercentre.com  No Resopnse            NaN
910  incometaxindiaefiling.gov.in  No Resopnse            NaN
932                n121adserv.com  No Resopnse            NaN
976       onlinecreditcenter6.com  No Resopnse            NaN
991                 bestadbid.com  No Resopnse            NaN
996             cocolog-nifty.com  No Resopnse            NaN

In [156]:
data[np.isnan(data['Response_Time'])].shape

(41, 3)

In [158]:
rec=[]
for website in df['URLS']:
    start=tm.time()
    try:
        ip = sc.gethostbyname(website.strip())
        end=tm.time()
        rec.append([website, ip,(end-start)])
    except sc.gaierror:
        rec.append([website, "No Resopnse",None])
rec

[[' google.com', '142.250.199.174', 0.09119248390197754],
 ['youtube.com', '142.250.67.174', 0.12022566795349121],
 ['facebook.com', '57.144.140.1', 0.20774626731872559],
 ['baidu.com', '13.127.247.216', 0.206193208694458],
 ['yahoo.com', '98.137.11.164', 0.0],
 ['amazon.com', '54.239.28.85', 0.0],
 ['wikipedia.org', '103.102.166.224', 0.20337486267089844],
 ['google.co.in', '142.251.42.67', 0.019369125366210938],
 ['twitter.com', '104.244.42.65', 0.1770644187927246],
 ['qq.com', '13.127.247.216', 0.011744499206542969],
 ['live.com', '204.79.197.212', 0.0],
 ['taobao.com', '59.82.122.130', 0.19797182083129883],
 ['bing.com', '150.171.27.10', 0.004876852035522461],
 ['google.co.jp', '142.250.196.163', 0.2354283332824707],
 ['msn.com', '204.79.197.219', 0.18742799758911133],
 ['yahoo.co.jp', '182.22.31.124', 0.180558443069458],
 ['linkedin.com', '13.107.42.14', 0.21495556831359863],
 ['sina.com.cn', '36.51.254.91', 0.4049968719482422],
 ['instagram.com', '57.144.140.34', 0.2103581428527832],
 ['weibo.com', '13.127.247.216', 0.20634913444519043],
 ['vk.com', '87.240.132.78', 0.0010576248168945312],
 ['yandex.ru', '5.255.255.77', 0.20037078857421875],
 ['google.de', '142.250.205.99', 0.09891533851623535],
 ['google.ru', '142.250.183.227', 0.09288334846496582],
 ['hao123.com', '110.242.69.86', 0.0],
 ['ebay.com', '23.202.229.140', 0.11777806282043457],
 ['reddit.com', '151.101.65.140', 0.18367433547973633],
 ['google.co.uk', '142.250.71.35', 0.12001252174377441],
 ['google.com.br', '142.250.182.35', 0.16628289222717285],
 ['mail.ru', '217.69.139.200', 0.23910903930664062],
 ['t.co', '172.66.0.227', 0.10944080352783203],
 ['pinterest.com', '151.101.0.84', 0.0],
 ['amazon.co.jp', '52.119.164.121', 0.20496678352355957],
 ['google.fr', '142.250.183.67', 0.10219788551330566],
 ['netflix.com', '18.200.8.190', 0.10132551193237305],
 ['gmw.cn', '47.93.60.29', 0.0],
 ['tmall.com', '59.82.133.135', 0.09919142723083496],
 ['360.cn', '106.63.103.5', 0.30977582931518555],
 ['google.it', '142.250.183.195', 0.20727014541625977],
 ['microsoft.com', '20.112.250.133', 0.0],
 ['onclickads.net', '139.45.197.105', 0.0],
 ['google.es', '142.250.183.227', 0.21409845352172852],
 ['paypal.com', '151.101.195.1', 0.09464621543884277],
 ['sohu.com', '61.135.164.50', 0.19088435173034668],
 ['wordpress.com', '192.0.78.17', 0.1036982536315918],
 ['tumblr.com', '192.0.77.40', 0.11581087112426758],
 ['blogspot.com', '142.250.205.9', 0.18454742431640625],
 ['imgur.com', '199.232.192.193', 0.0010387897491455078],
 ['xvideos.com', '13.127.247.216', 0.017491817474365234],
 ['google.com.mx', '142.251.42.67', 0.21412301063537598],
 ['naver.com', '223.130.192.247', 0.1026754379272461],
 ['stackoverflow.com', '172.64.155.249', 0.10390973091125488],
 ['apple.com', '17.253.144.10', 0.0013766288757324219],
 ['chinadaily.com.cn', '111.13.49.147', 0.0],
 ['fc2.com', '199.48.210.151', 0.28653955459594727],
 ['aliexpress.com', '47.246.173.237', 0.0065801143646240234],
 ['imdb.com', '52.94.228.167', 0.0],
 ['google.ca', '142.250.193.131', 0.1639254093170166],
 ['google.co.kr', '142.250.199.163', 0.15782809257507324],
 ['github.com', '20.207.73.82', 0.09603214263916016],
 ['ok.ru', '217.20.155.13', 0.015635967254638672],
 ['pornhub.com', '13.127.247.216', 0.15973424911499023],
 ['google.com.hk', '142.250.192.35', 0.14140701293945312],
 ['whatsapp.com', '57.144.141.32', 0.15895652770996094],
 ['diply.com', '162.159.129.73', 0.17530250549316406],
 ['jd.com', '211.144.27.126', 0.46223974227905273],
 ['amazon.de', '54.239.39.102', 0.17537426948547363],
 ['google.com.tr', '142.250.182.67', 0.15899276733398438],
 ['rakuten.co.jp', '133.237.180.69', 0.2379906177520752],
 ['craigslist.org', '208.82.238.129', 0.3544275760650635],
 ['office.com', '13.107.6.156', 0.04240298271179199],
 ['google.co.id', '142.250.192.67', 0.16380524635314941],
 ['kat.cr', '185.53.177.53', 0.0],
 ['amazon.in', '52.95.116.115', 0.17383027076721191],
 ['tianya.cn', 'No Resopnse', None],
 ['blogger.com', '142.250.67.169', 0.16585826873779297],
 ['google.pl', '142.251.42.35', 0.2743198871612549],
 ['nicovideo.jp', '18.164.144.103', 0.18085813522338867],
 ['alibaba.com', '47.246.137.105', 0.05719804763793945],
 ['soso.com', '43.153.236.147', 0.3018770217895508],
 ['pixnet.net', '103.23.108.107', 0.36408472061157227],
 ['google.com.au', '142.250.182.99', 0.1591501235961914],
 ['go.com', '13.248.150.189', 0.0],
 ['amazon.co.uk', '54.239.33.58', 0.2678563594818115],
 ['xhamster.com', '13.127.247.216', 0.17442870140075684],
 ['dropbox.com', '162.125.248.18', 0.06254911422729492],
 ['google.com.tw', '142.250.193.99', 0.16434788703918457],
 ['outbrain.com', '151.101.2.132', 0.32561206817626953],
 ['xinhuanet.com', '202.108.119.194', 0.0],
 ['cntv.cn', '163.171.205.108', 0.6008074283599854],
 ['googleusercontent.com', '142.250.206.65', 0.167252779006958],
 ['cnn.com', '151.101.131.5', 0.25142431259155273],
 ['ask.com', '199.232.106.114', 0.15814924240112305],
 ['coccoc.com', '123.30.175.29', 0.0],
 ['booking.com', '18.67.233.2', 0.2381458282470703],
 ['bbc.co.uk', '151.101.0.81', 0.15848851203918457],
 ['popads.net', '216.21.13.12', 0.0],
 ['youth.cn', '163.171.205.125', 0.569561243057251],
 ['twitch.tv', '151.101.2.167', 0.006781578063964844],
 ['wikia.com', '151.101.128.194', 0.0],
 ['microsoftonline.com', 'No Resopnse', None],
 ['quora.com', '34.239.7.197', 0.17296266555786133],
 ['chase.com', '146.143.83.57', 0.0],
 ['adobe.com', '23.211.137.97', 0.16184520721435547],
 ['163.com', '59.111.160.244', 0.001249551773071289],
 ['360.com', '104.192.110.232', 0.15860891342163086],
 ['haosou.com', '104.192.110.226', 0.449326753616333],
 ['google.com.pk', '142.250.71.99', 0.3090240955352783],
 ['google.co.th', '142.251.42.67', 0.16984820365905762],
 ['google.com.eg', '142.250.205.227', 0.23555445671081543],
 ['google.com.ar', '142.250.196.163', 0.31554746627807617],
 ['youku.com', '13.127.247.216', 0.15864849090576172],
 ['google.com.sa', '142.250.183.3', 0.3537118434906006],
 ['bbc.com', '151.101.0.81', 0.29723072052001953],
 ['flipkart.com', '163.53.76.86', 0.1671285629272461],
 ['alipay.com', '110.75.130.45', 0.0],
 ['bongacams.com', '13.127.247.216', 0.24396729469299316],
 ['adf.ly', '172.66.43.117', 0.16614508628845215],
 ['nytimes.com', '151.101.65.164', 0.26782894134521484],
 ['google.nl', '142.251.42.35', 0.1578202247619629],
 ['sogou.com', '43.153.249.87', 0.23689603805541992],
 ['livedoor.jp', '147.92.240.79', 0.0005955696105957031],
 ['daum.net', '211.249.220.24', 0.15806174278259277],
 ['txxx.com', '13.127.247.216', 0.3420755863189697],
 ['amazon.cn', '54.222.60.218', 0.010958194732666016],
 ['espn.go.com', '18.67.161.14', 0.3064124584197998],
 ['ebay.co.uk', '23.202.229.140', 0.15805339813232422],
 ['ettoday.net', '219.85.79.131', 0.009259223937988281],
 ['bankofamerica.com', '171.161.148.150', 0.0],
 ['china.com', 'No Resopnse', None],
 ['indiatimes.com', '23.58.62.151', 0.31116151809692383],
 ['myway.com', '199.232.46.114', 0.17073750495910645],
 ['bilibili.com', '47.103.24.173', 0.23516225814819336],
 ['walmart.com', '23.200.56.195', 0.1870741844177246],
 ['ebay.de', '23.58.144.143', 0.23051071166992188],
 ['china.com.cn', '202.130.245.42', 0.004813194274902344],
 ['godaddy.com', '208.109.192.70', 0.17025470733642578],
 ['dailymail.co.uk', '23.211.192.210', 0.23754048347473145],
 ['buzzfeed.com', '151.101.130.114', 0.17596793174743652],
 ['zillow.com', '216.137.52.103', 0.22120928764343262],
 ['xnxx.com', '13.127.247.216', 0.19078946113586426],
 ['salesforce.com', '23.1.35.132', 0.015167236328125],
 ['dailymotion.com', '13.127.247.216', 0.1714165210723877],
 ['wellsfargo.com', '184.86.112.121', 0.24914813041687012],
 ['detail.tmall.com', '13.127.247.216', 0.17462730407714844],
 ['steampowered.com', '23.8.247.132', 0.1262369155883789],
 ['steamcommunity.com', '23.58.59.27', 0.30802083015441895],
 ['nametests.com', '104.20.237.88', 0.17431116104125977],
 ['google.co.ve', '142.250.182.3', 0.13469862937927246],
 ['theguardian.com', '151.101.1.111', 0.0],
 ['google.com.ua', '142.250.77.35', 0.18202996253967285],
 ['indeed.com', '162.159.130.67', 0.17415595054626465],
 ['ameblo.jp', '199.232.214.133', 0.26058411598205566],
 ['aol.com', '76.223.84.192', 0.004359006881713867],
 ['etsy.com', '151.101.193.224', 0.0],
 ['globo.com', '186.192.83.12', 0.0008394718170166016],
 ['google.co.za', '142.250.71.35', 0.1800224781036377],
 ['yelp.com', '199.232.104.116', 0.12365365028381348],
 ['amazonaws.com', '72.21.206.80', 0.0010178089141845703],
 ['huffingtonpost.com', '151.101.66.114', 0.19284391403198242],
 ['tudou.com', '106.11.43.71', 0.3161039352416992],
 ['so.com', '104.192.110.226', 0.410872220993042],
 ['zhihu.com', '103.41.167.234', 0.20750117301940918],
 ['soundcloud.com', '18.164.144.97', 0.20479369163513184],
 ['tripadvisor.com', '151.101.2.28', 0.004696369171142578],
 ['google.gr', '142.250.193.163', 0.19356632232666016],
 ['varzesh3.com', '185.143.235.201', 0.10474371910095215],
 ['avito.ru', '176.114.120.24', 0.31111884117126465],
 ['onlinesbi.com', '103.68.221.190', 0.0005321502685546875],
 ['vice.com', '192.0.66.177', 0.08704590797424316],
 ['cnzz.com', '59.82.60.44', 0.3190171718597412],
 ['directrev.com', 'No Resopnse', None],
 ['uol.com.br', '200.147.35.149', 0.5079677104949951],
 ['bet365.com', '5.226.179.10', 0.0],
 ['weather.com', '23.36.31.139', 0.41440439224243164],
 ['mediafire.com', '13.127.247.216', 0.20196080207824707],
 ['uptodown.com', '151.101.131.52', 0.0],
 ['cnet.com', '34.149.196.126', 0.0],
 ['washingtonpost.com', '18.161.229.125', 1.1918408870697021],
 ['gfycat.com', 'No Resopnse', None],
 ['goo.ne.jp', '114.179.184.93', 0.30059242248535156],
 ['stackexchange.com', '172.64.144.30', 0.11029291152954102],
 ['force.com', '23.1.106.133', 0.10247254371643066],
 ['taboola.com', '151.101.130.132', 0.20547723770141602],
 ['google.com.co', '142.250.183.227', 0.22562098503112793],
 ['dmm.co.jp', '13.248.196.236', 0.18501973152160645],
 ['tuberel.com', '172.67.200.205', 0.09539556503295898],
 ['vimeo.com', '162.159.138.60', 0.03163576126098633],
 ['google.com.ng', '142.250.205.131', 0.19374728202819824],
 ['naver.jp', 'No Resopnse', None],
 ['feedly.com', '104.20.59.241', 0.10981178283691406],
 ['theladbible.com', '172.67.204.9', 0.0960550308227539],
 ['pixiv.net', '210.140.139.152', 0.11116266250610352],
 ['redtube.com', '13.127.247.216', 0.09538722038269043],
 ['detik.com', '103.49.221.211', 0.21513772010803223],
 ['homedepot.com', '35.201.95.83', 0.1015322208404541],
 ['torrentz.eu', '185.53.177.53', 0.0],
 ['slideshare.net', '151.101.2.152', 0.28740453720092773],
 ['google.ro', '142.251.42.35', 0.1271202564239502],
 ['taringa.net', '108.159.15.109', 0.20681023597717285],
 ['foxnews.com', '23.54.57.42', 0.005005836486816406],
 ['target.com', '151.101.2.187', 0.0],
 ['amazon.it', '52.95.116.114', 0.09164309501647949],
 ['google.com.pe', '142.250.183.99', 0.15810441970825195],
 ['flickr.com', '108.158.255.124', 0.15731406211853027],
 ['hclips.com', '91.227.144.58', 0.0],
 ['google.be', '142.250.192.67', 0.2055354118347168],
 ['amazon.fr', '52.95.116.113', 0.31807589530944824],
 ['9gag.com', '104.16.105.144', 0.19048810005187988],
 ['kakaku.com', '103.70.243.165', 0.15763592720031738],
 ['blogspot.in', '142.250.182.137', 0.15879249572753906],
 ['ikea.com', '23.215.194.104', 0.2187023162841797],
 ['mega.nz', '31.216.145.5', 0.1804826259613037],
 ['ifeng.com', '82.156.59.186', 0.0],
 ['udn.com', '23.58.14.197', 0.18280291557312012],
 ['web.de', '82.165.229.83', 0.17581701278686523],
 ['americanexpress.com', '118.215.83.54', 0.17217493057250977],
 ['iqiyi.com', '202.108.14.124', 0.00077056884765625],
 ['bp.blogspot.com', 'No Resopnse', None],
 ['fbcdn.net', '31.13.79.35', 0.1719961166381836],
 ['google.com.ph', '142.250.70.99', 0.20844364166259766],
 ['orange.fr', '81.52.142.219', 0.006946563720703125],
 ['comcast.net', '96.99.227.0', 0.0],
 ['google.com.sg', '142.250.182.99', 0.24172115325927734],
 ['terraclicks.com', '15.197.172.60', 0.0010209083557128906],
 ['youm7.com', '104.18.13.212', 0.17040491104125977],
 ['putlocker.is', '103.224.182.253', 0.1644270420074463],
 ['tribunnews.com', '18.67.161.48', 0.3003849983215332],
 ['gmx.net', '82.165.229.87', 0.008237361907958984],
 ['youporn.com', '13.127.247.216', 0.16814923286437988],
 ['deviantart.com', '18.155.107.23', 0.16787409782409668],
 ['nih.gov', '156.40.212.210', 0.4833853244781494],
 ['zol.com.cn', '110.43.213.6', 0.8171801567077637],
 ['ontests.me', 'No Resopnse', None],
 ['roblox.com', '128.116.104.3', 0.23638439178466797],
 ['doubleclick.net', '142.251.42.14', 0.1576533317565918],
 ['hdfcbank.com', '104.17.6.56', 0.3533284664154053],
 ['ozock.com', 'No Resopnse', None],
 ['tistory.com', '211.183.222.4', 0.0],
 ['capitalone.com', '204.63.43.34', 0.0],
 ['leboncoin.fr', '18.161.229.28', 0.17310810089111328],
 ['douyu.com', '129.227.213.118', 0.6877052783966064],
 ['google.cn', '142.250.192.3', 0.15805578231811523],
 ['51.la', '121.243.83.19', 0.6161127090454102],
 ['google.se', '142.250.193.163', 0.20598626136779785],
 ['spotify.com', '35.186.224.24', 0.1591348648071289],
 ['wikihow.com', '151.101.129.91', 0.0],
 ['onet.pl', '18.161.246.102', 0.20664691925048828],
 ['babytree.com', '60.205.255.187', 1.2721827030181885],
 ['w3schools.com', '76.223.115.82', 0.16989588737487793],
 ['upornia.com', '109.206.171.6', 0.017401695251464844],
 ['snapdeal.com', '18.172.64.31', 0.18767809867858887],
 ['forbes.com', '151.101.194.49', 0.010001182556152344],
 ['google.at', '142.250.183.3', 0.2306962013244629],
 ['wix.com', '199.15.163.133', 0.0],
 ['bestbuy.com', '23.207.180.175', 0.30142927169799805],
 ['livejournal.com', '81.19.74.1', 0.011860847473144531],
 ['mozilla.org', '35.190.14.201', 0.0],
 ['rdsa2013.com', 'No Resopnse', None],
 ['xfinity.com', '96.99.240.130', 0.34731411933898926],
 ['handycafe.com', '176.58.115.78', 0.0],
 ['groupon.com', '23.212.164.218', 0.1683516502380371],
 ['adnetworkperformance.com', '104.21.16.1', 0.2440645694732666],
 ['onedio.com', '18.161.229.52', 0.2921409606933594],
 ['thepiratebay.org', '13.127.247.216', 0.17651915550231934],
 ['skype.com', '20.76.201.171', 0.0],
 ['github.io', '185.199.109.153', 0.009966373443603516],
 ['allegro.pl', '5.134.213.80', 0.23207592964172363],
 ['google.dz', '142.250.182.227', 0.17782807350158691],
 ['google.com.vn', '142.250.205.227', 0.20078134536743164],
 ['paytm.com', '172.65.64.51', 0.03252983093261719],
 ['twimg.com', 'No Resopnse', None],
 ['wikimedia.org', '103.102.166.224', 0.35120081901550293],
 ['icicibank.com', '20.204.105.107', 0.1685013771057129],
 ['t-online.de', '34.246.241.220', 0.31516385078430176],
 ['tokopedia.com', '47.74.234.244', 0.11070561408996582],
 ['popcash.net', '172.67.71.61', 0.20667600631713867],
 ['telegraph.co.uk', '3.164.182.60', 0.20638608932495117],
 ['usps.com', '56.0.134.100', 0.387890100479126],
 ['slither.io', '172.67.4.156', 0.23616838455200195],
 ['wp.pl', '212.77.98.9', 0.1741170883178711],
 ['blog.jp', '147.92.146.242', 0.016870737075805664],
 ['google.ch', '142.250.195.99', 0.21509408950805664],
 ['webtretho.com', '123.30.128.200', 0.0],
 ['irctc.co.in', '103.252.142.27', 0.0],
 ['trello.com', '108.159.15.108', 0.1833643913269043],
 ['google.pt', '142.250.67.163', 0.22263765335083008],
 ['yesky.com', '49.4.62.169', 0.0],
 ['xywy.com', '180.163.29.151', 0.1895616054534912],
 ['huanqiu.com', '43.175.140.86', 0.4104580879211426],
 ['eksisozluk.com', '172.67.37.226', 0.2169957160949707],
 ['blastingnews.com', '212.97.32.174', 0.2142174243927002],
 ['citi.com', '192.193.218.80', 0.1886444091796875],
 ['shutterstock.com', '99.83.219.164', 0.2071857452392578],
 ['rediff.com', '23.215.7.9', 0.20270776748657227],
 ['files.wordpress.com', '192.0.72.2', 0.20454859733581543],
 ['ups.com', '153.2.228.130', 0.015642404556274414],
 ['1688.com', '140.205.174.2', 0.19923925399780273],
 ['google.cl', '142.250.195.131', 0.21840667724609375],
 ['bitauto.com', '18.161.229.103', 0.1852257251739502],
 ['speedtest.net', '151.101.130.219', 0.003546476364135742],
 ['pandora.com', '199.116.164.229', 0.3047177791595459],
 ['adexc.net', '172.67.130.148', 0.19012188911437988],
 ['imzog.com', '172.67.154.176', 0.2228860855102539],
 ['google.ae', '142.250.205.67', 0.1755051612854004],
 ['2ch.net', '104.20.87.225', 0.17526721954345703],
 ['google.cz', '142.250.205.99', 0.1674952507019043],
 ['loading-delivery2.com', '141.0.174.20', 0.0],
 ['seznam.cz', '77.75.77.222', 0.0],
 ['ltn.com.tw', '123.51.237.161', 0.002112150192260742],
 ['about.com', '151.101.2.137', 0.0],
 ['chaturbate.com', '13.127.247.216', 0.09943962097167969],
 ['ebay-kleinanzeigen.de', '3.78.7.130', 0.19166183471679688],
 ['slack.com', '13.126.138.201', 0.11046385765075684],
 ['mercadolivre.com.br', '15.197.170.90', 0.31095147132873535],
 ['google.co.il', '142.250.77.67', 0.20600271224975586],
 ['doorblog.jp', '147.92.146.242', 0.0007960796356201172],
 ['goodreads.com', '54.239.26.220', 0.10002660751342773],
 ['livejasmin.com', '109.71.161.200', 0.0],
 ['battle.net', '137.221.106.104', 0.1981046199798584],
 ['softonic.com', '151.101.193.91', 0.0],
 ['accuweather.com', '23.46.7.101', 0.31398677825927734],
 ['amazon.es', '54.239.33.90', 0.09381675720214844],
 ['wordpress.org', '198.143.164.252', 0.0],
 ['mbc.net', '34.235.77.171', 0.10998129844665527],
 ['slickdeals.net', '104.17.125.18', 0.09444761276245117],
 ['icloud.com', '17.253.144.10', 0.0],
 ['caijing.com.cn', '122.200.86.164', 0.0],
 ['google.hu', '142.250.195.227', 0.21287226676940918],
 ['kaskus.co.id', '103.6.117.2', 0.006214141845703125],
 ['wittyfeed.com', '16.170.207.214', 0.09843635559082031],
 ['fedex.com', '170.170.197.104', 0.39885497093200684],
 ['ndtv.com', '23.36.28.174', 0.10844707489013672],
 ['att.com', '144.160.36.42', 0.11077499389648438],
 ['mlb.com', '34.102.163.158', 0.0],
 ['kompas.com', '52.84.12.94', 0.10370016098022461],
 ['google.ie', '142.250.196.163', 0.022363901138305664],
 ['giphy.com', '151.101.65.91', 0.18785643577575684],
 ['usatoday.com', '199.232.46.62', 0.0],
 ['xcar.com.cn', '211.159.143.150', 0.0],
 ['hulu.com', '23.215.7.26', 0.09436440467834473],
 ['archive.org', '207.241.224.2', 0.09501242637634277],
 ['sberbank.ru', '194.54.14.168', 0.015650272369384766],
 ['media.tumblr.com', '74.114.154.18', 0.1592247486114502],
 ['pinimg.com', '151.101.64.84', 0.006773471832275391],
 ['messenger.com', '57.144.140.141', 0.05612063407897949],
 ['sourceforge.net', '104.18.12.149', 0.17602276802062988],
 ['oracle.com', '138.1.33.162', 0.11049675941467285],
 ['hp.com', '15.73.145.56', 0.0],
 ['lowes.com', '23.57.76.146', 0.10807943344116211],
 ['zendesk.com', '216.198.54.2', 0.09684920310974121],
 ['viralthread.com', '104.21.48.1', 0.11123490333557129],
 ['csdn.net', '124.70.25.132', 0.0],
 ['1905.com', '118.145.26.112', 0.0],
 ['mama.cn', '134.175.173.148', 0.0013387203216552734],
 ['youtube-mp3.org', 'No Resopnse', None],
 ['39.net', '211.99.98.81', 0.0],
 ['digikala.com', '185.188.104.10', 0.0],
 ['badoo.com', '31.222.67.112', 0.0],
 ['businessinsider.com', '151.101.65.171', 0.0],
 ['kinogo.co', '185.107.56.193', 0.0],
 ['weebly.com', '74.115.51.7', 0.016034603118896484],
 ['samsung.com', '211.45.27.231', 0.20523977279663086],
 ['abs-cbn.com', '23.61.202.189', 0.0006449222564697266],
 ['reimageplus.com', '161.47.7.14', 0.17387151718139648],
 ['airbnb.com', '54.243.237.216', 0.24256491661071777],
 ['sabah.com.tr', '194.36.160.50', 0.11023235321044922],
 ['wordreference.com', '148.251.52.149', 0.09481501579284668],
 ['hurriyet.com.tr', '83.66.162.26', 0.0],
 ['uefa.com', '13.69.68.39', 0.0],
 ['rambler.ru', '81.19.82.2', 0.2908308506011963],
 ['51yes.com', 'No Resopnse', None],
 ['cnnic.cn', '42.83.144.13', 0.015743255615234375],
 ['webmd.com', '207.231.204.56', 0.15996551513671875],
 ['ign.com', '151.101.129.135', 0.009546756744384766],
 ['liputan6.com', '35.190.21.225', 0.18903756141662598],
 ['dell.com', '143.166.30.172', 0.0],
 ['gizmodo.com', '104.26.2.63', 1.2672085762023926],

In [160]:
data = pd.DataFrame(rec, columns=["Website", "IP Address","Response_Time"])
data

               Website       IP Address  Response_Time
0           google.com  142.250.199.174       0.091192
1          youtube.com   142.250.67.174       0.120226
2         facebook.com     57.144.140.1       0.207746
3            baidu.com   13.127.247.216       0.206193
4            yahoo.com    98.137.11.164       0.000000
..                 ...              ...            ...
995        dream.co.id   178.128.127.87       0.207782
996  cocolog-nifty.com      No Resopnse            NaN
997             ptt.cc    140.112.172.5       0.127735
998         legacy.com     64.68.200.48       0.000000
999          mynet.com   212.101.122.34       0.000000

[1000 rows x 3 columns]

In [162]:
data.to_csv('IP_Addresses.csv')